### ISSUE TITLE
can this explain what the register web component does

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#100]
**What is missing from the application? Please describe.**
can this explain what the register web component does?  

**Describe the solution you'd like**
Addition to the README and short explanation in the yo prompts.  What's different if I say yes vs. no and why would I want to do one or the other?

**Describe alternatives you've considered**
long explanation in yo?

**Additional context**

**Comment by muenzpraeger** [comment]
It’ll be soon obsolete. It was an addition by KV.

Waiting for @caridy to merge this PR in.

https://github.com/salesforce/lwc/pull/1395

**Comment by caridy** [comment]
We are still bikeshedding on the name, but I plan to push for a consensus soon, and merge the PR.

**Comment by muenzpraeger** [comment]
Removing the UI option for now. It will be a breaking change anyway till the implementation lands.

**Comment by caridy** [comment]
The bikeshedding is now complete. We have chosen `MyComponent.CustomElementConstructor`, and @jodarove is cleaning up the RFC and the implementation, should land soon.
