### ISSUE TITLE
server:watch doesn't do anything

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#101]
### Summary

server watch isn't responding to changes in the source

### Steps To Reproduce:

1. create with ts, and custom express server
2. yarn watch:server (compiles, starts server as expected)
3. modify src/server/index.ts

### Expected result

server compiles/reloads

### Actual result

no compile/reload

**Comment by muenzpraeger** [comment]
Please check with latest `beta`. Still iterating on some of the mechanics (choosing between `nodemon` vs. `webpack`).
