### ISSUE TITLE
yarn serve fails with custom server config

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#103]
### Summary

serve is referring to something that doesn't exist with ts project?

### Steps To Reproduce:

create app with ts/yarn/express
yarn build
yarn serve

### Expected result

server starts

### Actual result

⚡⚡⚡⚡⚡  Lightning Web Components ⚡⚡⚡⚡⚡

TypeError: customExpressConfig is not a function
    at Serve.run (~/code/test-lwc-client-server/node_modules/lwc-services/lib/commands/serve.js:42:13)
    at Serve._run (~/code/test-lwc-client-server/node_modules/@oclif/command/lib/command.js:44:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
Yup, that's this one...

https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/src/commands/serve.ts#L78
