### ISSUE TITLE
beta14: can't run watch because run-p is not installed

### ISSUE THREAD

**Issue by pozil** [muenzpraeger/create-lwc-app#105]
When trying to run watch in beta 14, there will be an error because `run-p` is not available (it's not installed by default).
I assume that you have it installed at global level so you did not notice this issue.

**Comment by muenzpraeger** [comment]
Good catch! Wasn't installed globally (never a fan of that), but only in the local test project.

**Comment by muenzpraeger** [comment]
So, I just ran `beta14`, and `run-p` works as expected as it's installed by default as devDependency.

Can you please clarify/post the error? Thanks!

**Comment by pozil** [comment]
This is crazy, I just reinstalled the whole thing and it works now.
I had some sort of "command not found: run-p" error message earlier but unfortunately I didn't keep the trace.
Could there be some sort of cache issue?

**Comment by muenzpraeger** [comment]
I don't think so, the `v14` is a couple of days old.
