### ISSUE TITLE
Define register / createElement / buildCustomElementConstructor for TS

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/create-lwc-app#199]
**What is missing from the application? Please describe.**

Personally I put this in `src/types/lwc.ts`, but there might be a way to do this in `lwc-services`?

```typescript
// import * as lwc from 'lwc';

declare module 'lwc' {

    // register
    export const register: any;

    // createElement
    type ShadowDomMode = 'open' | 'closed';
    interface CreateElementOptions {
        is: ComponentConstructor;
        mode?: ShadowDomMode;
    }
    export function createElement(sel: string, options: CreateElementOptions): HTMLElement;

    // buildCustomElementConstructor
    export interface LightningElementConstructor {
        new (): LightningElement;
        readonly prototype: LightningElement;
    }
    export interface ComponentConstructor extends LightningElementConstructor {
        readonly name: string;
        readonly labels?: string[];
        readonly delegatesFocus?: boolean;
    }
    export interface HTMLElementConstructor {
        prototype: HTMLElement;
        new (): HTMLElement;
    }
    export function buildCustomElementConstructor(
        Ctor: ComponentConstructor,
        options?: ShadowRootInit
    ): HTMLElementConstructor
}
```

**Describe the solution you'd like**
Add these three functions to suppress errors.

- `register` for wires, this can just be `any`.
- `createElement` for jest tests
- `buildCustomElementConstructor` for setting up the app in `index.ts`

**Describe alternatives you've considered**
Living with red squiggles.

**Additional context**
There are probably other ways to fix this, but I've been using this.

**Comment by muenzpraeger** [comment]
This will be part of the VS Code LWC Language server enhancements, see [here](https://github.com/forcedotcom/lightning-language-server/pull/16).


Also `buildCustomElementConstructor` will go away. Once @caridy got to it... ;-)

https://github.com/salesforce/lwc/pull/1395

**Comment by Templarian** [comment]
Sorry for the confusion, but how does that language server fix TS errors in other editors?

Diego said they were left out on purpose, but it seems weird to leave them out of Open Source as they are used.

**Comment by muenzpraeger** [comment]
The LWC Language Server provides more capabilities then just d.ts files. For example auto completion, hover help and so forth.

It is/should be generic, so you can extend/use the above linked open source project for usage in other IDE‘s.

Nick did a great session about that here:

https://youtu.be/eB0VoYOb2V8
