### ISSUE TITLE
beta22: resolveModules no longer exported in @lwc/module-resolver

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/create-lwc-app#202]
### Summary

I just updated to .22 and it looks like it switched `@lwc/*` deps. Looks like this version doesn't export resolveModules.

### Steps To Reproduce:

1. Update `lwc-services` to beta22 in a project
2. `yarn/npm watch`

### Expected result

Should compile.

### Actual result

Seeing an exception due to not finding `resolveModules`.

### Additional information

`@lwc/module-resolvers`: https://github.com/salesforce/lwc/blob/v1.0.2-222.18/packages/@lwc/module-resolver/src/index.ts#L117

`change`: https://github.com/muenzpraeger/create-lwc-app/pull/201/files#diff-79b3b8ab9015e7b57dcae182abaab9abR21

**Comment by muenzpraeger** [comment]
Known. The 1.1.0 alpha‘s are missing deps. And 1.0.2 doesn’t have the new module resolution (as you point out here).

I am already talking to Diego to pin down what version to use now. ;-)
