### ISSUE TITLE
Prettier Markdown Autofix

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/create-lwc-app#222]
### Summary

Need to test on a clean project, but I think prettier might not be setup to auto format markdown files that contain `lwc` html.

### Steps To Reproduce:

1.  Create markdown file with `<c-foo attribute={test}>`
2. Verify that it doesn't try to fix it to `<c-foo attribute="{test}">`

### Expected result

Should keep formatting on attributes.

### Actual result

Quotes are added.

### Additional information

I'll try and debug this but might be busy the next few days.

**Comment by muenzpraeger** [comment]
Tested and could not reproduce.

**Comment by Templarian** [comment]
Just tried with latest:

````html
This:
```html
<test-this attr={test}>
    Awesome
</test-this>
```
is becoming...
```html
<test-this attr="{test}">
    Awesome
</test-this>
```
````

**Comment by muenzpraeger** [comment]
Got it, with the addition `html` specification.

That's not related to `create-lwc-app`. I recommend to open an issue against the [Prettier repo](https://github.com/prettier/prettier/issues). Especially as @ntotten and team maintain it. ;-)
