### ISSUE TITLE
Webpack treeshaking support

### ISSUE THREAD

**Issue by khangsfdc** [muenzpraeger/create-lwc-app#223]
### Summary

Webpack config does not appear to be configured to use tree-shaking (https://webpack.js.org/guides/tree-shaking/).

### Steps To Reproduce:
```
src
  modules
    app
      app.js
    treeshake
      treeshake.js
```

```javascript
// treeshake.js
const used = "foo";
const unused = "bar";
export {
    used,
    unused
};
```

```javascript
// app.js
import { LightningElement } from 'lwc';
import {used} from 'my/treeshake';
console.log(used)
export default class App extends LightningElement {}
```
### Expected result

`export unused` should not be included in webpack bundle.

### Actual result

`export unused` is included in the bundle:

```javascript
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "used", function() { return used; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "unused", function() { return unused; });
const used = "foo";
const unused = "bar";
```

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
It is on purpose. The app developer knows their application best, so they can/should decide themselves if they apply `unusedExports` or `sideEffects` in webpack.

As you can pass your own custom webpack config using the `-w` flag to the build process you've complete control over customizing it.
