### ISSUE TITLE
module fails to use a ts class with default property values

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#283]
### Summary

error in module parsing where a module references a TS exported class that has properties with default values.
 
### Steps To Reproduce:

1. create ts class
``` typescript
class Tester {
  prop: number = 5;
}
export { Tester }
```
import that class in an LWC 
``` typescript
import { Tester } from '../tester';

export default class TestLWC extends LightningElement {
  @track var: Tester;
}
```

### Expected result

builds
### Actual result

unexpected token at the point where the ts class sets a default value.

### Additional information

ERROR in ./src/server/lib/CDS.ts 6:18
Module parse failed: Unexpected token (6:18)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   // when the open button became visible, even if more scripts were still running
|   // how many lines need to run...used for status bar
>   additionalUsers = [];
|   errors = [];
|   commandResults = [];
 @ ./src/client/modules/route/deployMessages/deployMessages.ts 5:0-49 20:23-26
 @ ./src/client/modules/structure/main/main.html
 @ ./src/client/modules/structure/main/main.js
 @ ./src/client/index.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./src/client/index.js

**Comment by muenzpraeger** [comment]
Is that still happening? Just tried, and I'm not getting an error.

<img width="1271" alt="2020-01-25_07-57-42" src="https://user-images.githubusercontent.com/2205451/73117607-774dbd00-3f48-11ea-819b-6225eaee7423.png">
