### ISSUE TITLE
Missing ability to set flags on the node runtime

### ISSUE THREAD

**Issue by sbougonSF** [muenzpraeger/create-lwc-app#297]
**What is missing from the application? Please describe.**
Node can not be launched with parameters (see context below). Example given:
`node --max-http-header-size 80000`

**Describe the solution you'd like**
it'd be nice to be able to specify node parameters in the lwc-services.config.js or read them from the environment

**Describe alternatives you've considered**
I forked create-lwc-app and modified the run script and added my param after the shebang, to unblock me

**Additional context**
My application is a LWC application which displays loglines from Splunk. These logline are passed as a query param. Because of a CVE, node reduced the size of the URL to 8K, and my app can not display most of the loglines (see this [node commit for the 8K limitation](https://github.com/nodejs/node/commit/186035243fad247e3955fa0c202987cae99e82db) and this [release note](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-12-26-version-10150-dubnium-lts-mylesborins) for the node parameter) unless I specify a bigger size via the --max-http-header-size flag

**Comment by muenzpraeger** [comment]
As it's using `webpack` does this work for you?

```
"watch": "NODE_OPTIONS='--max-http-header-size=100000' lwc-services watch"
```

**Comment by sbougonSF** [comment]
ah yes, perfect !
