### ISSUE TITLE
having a component importing slds legacy throws

### ISSUE THREAD

**Issue by reiniergs** [muenzpraeger/create-lwc-app#320]
### Summary
Having a component that contains a CSS import like: `@import  "@salesforce/slds/legacy"; throws a parsing error
```
Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.o
rg/concepts#loaders
| /*! Lightning Design System 2.11.0-beta.1 */
> @charset "UTF-8";
| .slds-file-selector {
|   display: -webkit-inline-box;
```

### Steps To Reproduce:
1. Install specifically SLDS 2.11.0-beta.1
2. go to any component css file and add `@import "@salesforce/slds/legacy";`
3. `yarn build` check in the console the errors

### Expected result
The app should build correctly

### Root cause
the loader is ignoring css file because the path included here https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/src/utils/webpack/webpack-builder.ts#L128 is not being correctly computed

here is where is computing the `npms` value
https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/src/utils/webpack/webpack-builder.ts#L6

for 
```
{
        "name": "@salesforce/slds/legacy",
        "path": "assets/styles/salesforce-lightning-design-system-imports.sanitized.css"
}
```
the implementation will map `<projectRoot>/node_modules/@salesforce-ux/design-system/assets/styles/`

the correct value should be `<projectRoot>/node_modules/@salesforce-ux/design-system/`

note: the current solution will work for some use cases, but not for `@salesforce-ux/design-system` because the entry point is doing some relative import from ignored directories.

e.g.
salesforce-lightning-design-system-imports.sanitized.css
```
@import '../../css/common/index.css';
@import '../../css/accordion/base/index.css';
@import '../../css/avatar/base/index.css';
```

**Comment by muenzpraeger** [comment]
As mentioned in the email thread the value for `npms` is a result of the module resolver from `@lwc/module-resolver`. Not sure how to solve that.

Thoughts, @diervo?

**Comment by diervo** [comment]
Seems that the module resolver is working fine standalone, so not sure how is it failing here, probably something to do with Webpack? I can debug with @reiniergs and provide a PR

**Comment by muenzpraeger** [comment]
To me it look like it‘s a CSS loader issue. Which may be just solved with a custom webpack config.

**Comment by joeattardi** [comment]
Any possible solution to this yet? I am trying to use the SLDS styling on an app created with create-lwc-app but haven't had success yet. I tried @importing the SLDS stylesheet from my component CSS file - not sure if this is even the best way to do that - and I'm getting the same error.

**Comment by muenzpraeger** [comment]
This is not supported and won’t be supported for some time.

**Comment by joeattardi** [comment]
Ok, thank you.
