### ISSUE TITLE
Jest debug fails

### ISSUE THREAD

**Issue by xyc** [muenzpraeger/create-lwc-app#347]
### Steps To Reproduce:

1.  Create a new app from `create-lwc-app`
1.  Execute `yarn run test:unit:debug`
1. Go to chrome://inspect and inspect the debug 

It fails with "Cannot find module" error
<img width="975" alt="Screen Shot 2019-12-02 at 6 16 26 PM" src="https://user-images.githubusercontent.com/679275/70014711-4183ed80-1530-11ea-87cc-4582b34c5486.png">

### Expected result

Debug successfully

### Actual result

Fails with error

### Additional information
Looking at the implementation, it looks up jest from `../../node_modules` which is two directories up. If I change it to `./node_modules` I can successfully debug my tests.

https://github.com/muenzpraeger/create-lwc-app/blob/d8bd8fd4cb95ec752e02c5133b95a1ff1a3cdfc3/packages/lwc-services/src/commands/test/unit.ts#L77-L80

**Comment by muenzpraeger** [comment]
Thanks for catching that.

I just published `lwc-services@1.3.12-beta.0` to fix that. LMK if that works for you.

**Comment by xyc** [comment]
Thanks @muenzpraeger for looking into this! Yes `lwc-services@1.3.12-beta.0` fixes this issue.

**Comment by muenzpraeger** [comment]
Cool, will update `lwc-services` soon then.
