### ISSUE TITLE
Respect passthrough arguments in Jest Debug

### ISSUE THREAD

**Issue by xyc** [muenzpraeger/create-lwc-app#350]
### Summary
The use case: (to support LWC OSS projects W-6975995) in LWC VS Code extension (https://github.com/forcedotcom/salesforcedx-vscode/issues/1703), we'd want to pass additional jest arguments like`--testNamePattern`, `--json` to debug specific test with name or report test results & failure messages when debugging.

### Steps To Reproduce:

When running with `--debug` flag, `lwc-services test:unit` doesn't respect Jest command line flags if `--passthrough` is specified

### Expected result

`lwc-services test:unit` should respect `--passthrough` argument

### Additional information
In debug arguments:
https://github.com/muenzpraeger/create-lwc-app/blob/d8bd8fd4cb95ec752e02c5133b95a1ff1a3cdfc3/packages/lwc-services/src/commands/test/unit.ts#L82
it doesn't pass in the passthrough arguments like
https://github.com/muenzpraeger/create-lwc-app/blob/d8bd8fd4cb95ec752e02c5133b95a1ff1a3cdfc3/packages/lwc-services/src/commands/test/unit.ts#L108-L110

**Comment by muenzpraeger** [comment]
Let me know if `lwc-services@1.3.12-beta.1` fixes that for you.

**Comment by xyc** [comment]
Yes, `lwc-services@1.3.12-beta.1` fixes this issue. Thank you for the quick turnaround @muenzpraeger !

**Comment by muenzpraeger** [comment]
Cool. I’m gonna publish a new non-beta early next week.
