### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by ankushsomani09** [muenzpraeger/create-lwc-app#352]
Error: EPERM: operation not permitted, mkdir 'C:/Windows/System32/conference-app'
    at CreateGenerator.prompting (C:/Users/AL1840/AppData/Roaming/npm-cache/_npx/23880/node_modules/create-lwc-app/lib/generators/createGenerator.js:286:16)

while running this "npx create-lwc-app conference-app"
above issue appeared after step : 11 Windows only: Do you want to use Edge as browser: Enter y if you want to be able to use Edge and press Enter to confirm the selection.

npm version:
C:\Windows\System32>npm version
{
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.14.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}

How to solve this

**Comment by muenzpraeger** [comment]
You’re trying to create the directory `conference-app` in the Windows system directory, where you don’t have write permissions. Execute the command from a directory where you can write.

**Comment by ankushsomani09** [comment]
Really appreciate your help.  By d way you created nice slider in Trailheadx India. :)
