### ISSUE TITLE
npm run watch give errors

### ISSUE THREAD

**Issue by ankushsomani09** [muenzpraeger/create-lwc-app#353]
### Summary

'nodemon' is not recognized as an internal or external command

### Steps To Reproduce:

1.  run : npm run watch, get this error : "'nodemon' is not recognized as an internal or external command" 
2. To solve it, I run this "npm install -g nodemon"
3.  run again : "npm run watch"\

### Actual result
`C:\Users\AL1840\Documents\conference-app>npm run watch

> conference-app@0.0.0 watch C:\Users\AL1840\Documents\conference-app
> run-p watch:client watch:server

> conference-app@0.0.0 watch:client C:\Users\AL1840\Documents\conference-app
> lwc-services watch

> conference-app@0.0.0 watch:server C:\Users\AL1840\Documents\conference-app
> nodemon

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src\server\**\*.js scripts\express-dev.js
[nodemon] watching extensions: js
[nodemon] starting `node ./scripts/express-dev.js`
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- C:\Users\AL1840\Documents\conference-app\scripts\express-dev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\AL1840\Documents\conference-app\scripts\express-dev.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\AL1840\\Documents\\conference-app\\scripts\\express-dev.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
(node:26836) [ENOTDIR] Error Plugin: lwc-services: ENOTDIR: not a directory, scandir 'C:\Users\AL1840\Documents\conference-app\lwc-services'
module: @oclif/config@1.13.3
task: toCached
plugin: lwc-services
root: C:\Users\AL1840\Documents\conference-app\node_modules\lwc-services
See more details with DEBUG=*
(node:26836) [ENOTDIR] Error Plugin: lwc-services: ENOTDIR: not a directory, scandir 'C:\Users\AL1840\Documents\conference-app\lwc-services'
module: @oclif/config@1.13.3
task: toCached
plugin: lwc-services
root: C:\Users\AL1840\Documents\conference-app\node_modules\lwc-services
See more details with DEBUG=*
(node:26836) [ENOTDIR] Error Plugin: lwc-services: ENOTDIR: not a directory, scandir 'C:\Users\AL1840\Documents\conference-app\lwc-services'
module: @oclif/config@1.13.3
task: toCached
plugin: lwc-services
root: C:\Users\AL1840\Documents\conference-app\node_modules\lwc-services
See more details with DEBUG=*
 »   Warning: watch is not a lwc-services command.
Did you mean serve? [y/n]:`

**Comment by muenzpraeger** [comment]
That looks like your dependencies didn’t get set up properly. Just re-run the app creation.

**Comment by ankushsomani09** [comment]
Getting this in between while re-run :
```
> husky@3.1.0 install C:\Users\AL1840\Documents\conference-app\conference-app\node_modules\husky
> node husky install

husky > Setting up git hooks
ENOENT: no such file or directory, mkdir 'node_modules\husky\.git\hooks'
husky > Failed to install
```

**Comment by muenzpraeger** [comment]
Looks like something is messing up with your environment during the installation process (as in: dependencies are not installed).

What version of `node` or `yarn` are you using?

**Comment by ankushsomani09** [comment]
```
C:\Users\AL1840\Documents\conference-app>npm run watch

> conference-app@0.0.0 watch C:\Users\AL1840\Documents\conference-app
> run-p watch:client watch:server


> conference-app@0.0.0 watch:client C:\Users\AL1840\Documents\conference-app
> lwc-services watch


> conference-app@0.0.0 watch:server C:\Users\AL1840\Documents\conference-app
> nodemon

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! conference-app@0.0.0 watch:server: `nodemon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conference-app@0.0.0 watch:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AL1840\AppData\Roaming\npm-cache\_logs\2019-12-25T13_02_14_912Z-debug.log
ERROR: "watch:server" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! conference-app@0.0.0 watch: `run-p watch:client watch:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conference-app@0.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AL1840\AppData\Roaming\npm-cache\_logs\2019-12-25T13_02_15_189Z-debug.log

C:\Users\AL1840\Documents\conference-app>
```

**Comment by ankushsomani09** [comment]
npm  version

{
  'conference-app': '0.0.0',
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.14.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}

**Comment by ankushsomani09** [comment]
Problem is Express and Nodemon dependency are not creating while running this "npx create-lwc-app conference-app".
If I have to install both seperatly, what should be perfect way, as I have already tried but getting new errors after that.
