### ISSUE TITLE
importable LWC

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#382]
**What is missing from the application? Please describe.**
import of publicly defined modules

**Describe the solution you'd like**
Let's say people are building/publishing LWC via npm.  I want to use someone else's **card** or **button** or reuse them across projects.

It'd be nice to adopt what webcomponents.org did and just let people install via npm: https://www.webcomponents.org/element/@polymer/paper-button

Then you'd just need some way to tell the module compiler where these are (obviously, they'd be in node_modules, but not everything there is an LWC.  So either a secondary command to import it to the project, OR some list of LWC's that reside within node_modules.

**Describe alternatives you've considered**
some cli command that imports them AND then either 1) moves them to the project via copy?  I don't want to lose all the dependencies and npm versioning/update goodness so coming up with a way to use native npm seems better.

**Additional context**
People are going to want to do similar things with on-platform LWC, so solving this in a broader context might be wise.

**Comment by muenzpraeger** [comment]
That’s something for the LWC framework to provide/solve.

**Comment by mshanemc** [comment]
or, run a separate subset of npm packages like https://www.webcomponents.org/publish

**Comment by muenzpraeger** [comment]
Technically you can already use npm published components. It’s already used in an unofficial version [here](https://github.com/trailheadapps/lwc-recipes-oss/blob/master/package.json#L9) in LWC Recipes.

Having said that the overall module resolution is still in flux. You should weigh in [here](https://github.com/salesforce/lwc-rfcs/pull/20).

**Comment by mshanemc** [comment]
@muenzpraeger that is exactly what I'm trying to do.  Thanks!

**Comment by mshanemc** [comment]
ehh, kind of.  For your lwc-recipes-oss, leaving things in the most basic configuration seems to work automagically.  If you did a client/server approach, you have to give it more hints:

``` js
module.exports = {
    resources: [{ from: 'src/client/resources', to: 'dist/resources' }],
    sourceDir: './src/client',
    moduleDir: './src/client/modules',
    localModulesDirs: ['./node_modules/@mshanemc/lwc-oss-base/src/modules']
};
```

**Comment by muenzpraeger** [comment]
No, you don’t. The module configuration is what the npm package that you _consume_ should provide. The LWC module resolver does the rest automatically.

When you install the zu package from recipes and inspect the `lwc` key in its `package.json` you‘ll see how. Again, this is in flux and can break.
