### ISSUE TITLE
component creation script

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#42]
**What is missing from the application? Please describe.**
I want to create new LWC (folder + 3 files) but not do it manually.

**Describe the solution you'd like**
lwc:create -n myNewLWC -d src/modules/namespace

**Describe alternatives you've considered**
manually creating files, adding an sfdx project.json just to get lwc:create in vscode

**Additional context**
Already wrote this in my plugins for my own use...this is to share into the LWC OSS tooling
https://github.com/mshanemc/shane-sfdx-plugins/tree/master/src/commands/shane/lwc

**Comment by muenzpraeger** [comment]
Thanks for bringing that up. It's a well known pain point (for me). At the same time there is another tooling initiative coming that'll fix this in another way

I'll keep this issue open till then.

**Comment by muenzpraeger** [comment]
Will be incorporated into the Salesforce VS Code extensions.

**Comment by mrigdon** [comment]
So no command line way? Does this mean everyone has to use VSCode? (I prefer Atom)

**Comment by muenzpraeger** [comment]
Yeah, no command line way. Technically you‘d only need two snippets anyway for that.

The bigger part will also be that the LWC Language Server gets now LWC OSS support.

https://github.com/forcedotcom/lightning-language-server/pull/16

**Comment by muenzpraeger** [comment]
Closing this, as it's tracked in the language server repo.
