### ISSUE TITLE
Completed Trailhead Module continues to throw errors in Local Dev Server even though it works in Dev Org

### ISSUE THREAD

**Issue by muel8192** [muenzpraeger/create-lwc-app#421]
### Summary
I completed the Trailhead module:  https://trailhead.salesforce.com/content/learn/projects/lwc-build-flexible-apps after having previously completed this Trailmix: http://sforce.co/df19-devtrailmix 

After completing the Bear Tracking App, it works as expected in my Dev Org, but throws errors and appears differently in the Local Development Server. I'm not sure if there is a difference between how the Local Dev Server works when creating a project with the npx command or running it from the VS Code commands, but in this case, I ran it from the VS Code commands. I had not created the project with the npx command. @muenzpraeger , I apologize if this is not the right place to post this.

### Steps To Reproduce:

1.  Complete and pass this module: https://trailhead.salesforce.com/content/learn/projects/lwc-build-flexible-apps while running Local Development Server.
2. Realize that even though you pass the Trailhead and things work in your Dev Org, they throw errors and don't appear correctly in the Local Dev Server.
3. Close all programs.
4. Reopen VS Code and verify you are in the folder that you completed the Bear app in.
5. Authorize the org by running:  sfdx force:auth:web:login -s -a bear-tracking
6. Start the Local Development Server as instructed here:  https://developer.salesforce.com/tools/vscode/en/lwc/localdev/
From VS Code’s command palette type in “local development,” then select SFDX: Start Local Development Server
7. Observe differences.

### Expected result

Not to get errors in Local Server and components to appear the same way.

### Actual result
Home Page In Org - Working As Expected (the magnifying glass does bring you to a bears details and clicking on a bear in the map or the map list does produce the bear coordinates)
![HomePageInOrg_WorkingAsExpected](https://user-images.githubusercontent.com/29761273/73601376-5d0a7500-452e-11ea-80c9-3024a774cdb3.jpg)

Bear List - Displaying as expected in the LocalHost (the magnifying glass does not work here, as expected)
![BearListLocalHost](https://user-images.githubusercontent.com/29761273/73601386-8c20e680-452e-11ea-997f-6828c5d91fa3.jpg)

Bear Map - Error in LocalHost
![BearMapLocalHost](https://user-images.githubusercontent.com/29761273/73601409-18cba480-452f-11ea-806f-4e92c8d689b3.jpg)

Bear Tile - Error in LocalHost
![BearTileLocalHost](https://user-images.githubusercontent.com/29761273/73610609-481df800-45a7-11ea-8923-431acefa1f88.jpg)

Search For SA in Org - working as expected
![SearchForSAInOrg](https://user-images.githubusercontent.com/29761273/73610632-73084c00-45a7-11ea-9c6d-b659bcad6c28.jpg)

Search For SA in LocalHost - Tiles not aligned properly
![SearchForSALocalDevelopment](https://user-images.githubusercontent.com/29761273/73610650-9f23cd00-45a7-11ea-9133-d766b5b67504.jpg)

Search For P in Org - Tiles are aligned as expected, but list of bears disappears from map
![SearchForPInOrg](https://user-images.githubusercontent.com/29761273/73610666-e6aa5900-45a7-11ea-9e02-f5edf36b4c43.jpg)

Search For P in in LocalHost - Tiles not aligned properly
![SearchForPLocalDevelopment](https://user-images.githubusercontent.com/29761273/73610676-0c376280-45a8-11ea-8f41-76baf2ec2b36.jpg)

**Comment by muenzpraeger** [comment]
Can you please open an issue on [this repository](https://github.com/forcedotcom/lwc-dev-server-feedback/issues)? That's the right place. Thanks!
