### ISSUE TITLE
Instalation ERROR

### ISSUE THREAD

**Issue by Marcelovv2** [muenzpraeger/create-lwc-app#422]
Windows 10 64 bit, node 12.15.0, npm 6.13.7
I'm following https://lwc.dev/guide/install#tools and encounter errors at the beginning,

`salesforce> npx create-lwc-app mvv-app
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/typescript-estree@2.19.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@typescript-eslint/parser'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\marce\AppData\Roaming\npm-cache_logs\2020-02-10T20_26_01_533Z-debug.log
Install for [ 'create-lwc-app@latest' ] failed with code 1`

As mention here: https://github.com/salesforce/lwc/issues/1718#issuecomment-584344950, issue also find on mac

**Comment by muenzpraeger** [comment]
Does this still happen? There seemed to be a problem with their `npm` package which seems to be resolved now.

https://github.com/typescript-eslint/typescript-eslint/issues/1588

**Comment by Marcelovv2** [comment]
No is not happening anymore, thanks

**Comment by Marcelovv2** [comment]
.
