### ISSUE TITLE
Rename to create-lwc-app to enable invocation shorthands

### ISSUE THREAD

**Issue by jdalton** [muenzpraeger/create-lwc-app#43]
Hi @muenzpraeger 👋,

**What is missing from the application? Please describe.**

Renaming `lwc-create-app` to `create-lwc-app` will enable shortcuts like:
```js
yarn create lwc-app
npm init lwc-app
npm create lwc-app
```

See docs for [`yarn create`](https://yarnpkg.com/en/docs/cli/create) and [`npm init`](https://docs.npmjs.com/cli/init).

**Comment by muenzpraeger** [comment]
I’ve chosen on purpose to not use that option.

Global installed scripts tend to not get updated often. Especially for the first release iterations I expect frequent changes, that’s why it’s the `npx` way of things. IF someone really wants to install it globally they should do it on purpose. ;-)

At the same time the tool and OSS launch is now out, so I’m hesitant to change naming during flight. Especially as it would mean in the long run breaking changes.

**Comment by jdalton** [comment]
Using `yarn create` should install or update the `<starter-kit-package>` package automatically. For `npm init`, and its alias `npm create`, `npm` [uses `npx` under the hood](https://github.com/npm/cli/commit/008a83642e04360e461f56da74b5557d5248a726).

**Comment by muenzpraeger** [comment]
Got it. Still there’s the naming concern. I let this settle for a bit, and will revisit for a later release.

**Comment by jdalton** [comment]
For naming you can do a couple things to help migration. You can have the existing package [deprecated](https://docs.npmjs.com/cli/deprecate) _(you may choose to do a major version bump and deprecate that major range)_. Deprecating removes the package from the npm website search and displays a deprecation message in the console. You can also update the readme to reflect the migration to echo the deprecation message. Then update docs to the new package name.

**Comment by muenzpraeger** [comment]
I know. It’s just that changing the naming a week after the initial release is just not a good thing.

**Comment by jdalton** [comment]
Cool, cool. Thank you!

**Comment by muenzpraeger** [comment]
Will be changed in the next release (release likely end of week).

**Comment by muenzpraeger** [comment]
You can already experiment with it on the `beta` channel. ;-)
