### ISSUE TITLE
Running into an unexpected JSON Input while parsing ... 

### ISSUE THREAD

**Issue by jalapagos** [muenzpraeger/create-lwc-app#477]
I've been trying to setup my `LWC OSS` application by following the installation on `lwc.dev`. Keep running into the following issue : 

`Unexpected end of JSON input while parsing near '...gq68EBMseLKC72k3wFmwt'`

When I `cat` the debug log this is what I see (shortened) : 

![Screen Shot 2020-03-10 at 8 16 45 PM](https://user-images.githubusercontent.com/13071102/76378974-1584bf00-630c-11ea-9b59-cb6812a1c863.png)

Any idea what might be the issue?

**Comment by muenzpraeger** [comment]
That's an error with `npm`, not much an I can do. Sorry.
