### ISSUE TITLE
Example config lwc-services.config.js does not exist in repo

### ISSUE THREAD

**Issue by paustint** [muenzpraeger/create-lwc-app#486]
### Summary
There are a couple of places (readme and https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/create-lwc-app/templates/lwc-services.config.js) that make mention of an example `lwc-services.config.js` file, but the link is broken.

**Is there somewhere else where this is documented?**

### Steps To Reproduce:

1.  Go to readme and find this part:
> If you want to override certain behavior of lwc-services you can place a lwc-services.config.js file into the root of your app directory. Checkout [the example file](https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/example/lwc-services.config.js) for possible configuration parameters and values.

1.  Click the link "this example file" https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/example/lwc-services.config.js
1. Page not found - 404
1. Manual attempt to find the file and notice it does not exist in the repo

##### Alternate steps:

1. Open `lwc-services.config.js` in a newly created project
2. click the link in the file
3. 404

```javascript
// Find the full example of all available configuration options at
// https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/lwc-services/example/lwc-services.config.js
module.exports = {
    resources: [{ from: 'src/resources', to: 'dist/resources/' }]
};

```

### Expected result

The link to the example file works.

### Actual result

404

### Additional information

I eventually found this to work around the broken url: https://github.com/muenzpraeger/create-lwc-app/blob/5e5f4d69e6d3d7a0072b9f5eda269b7b42630041/packages/lwc-services/src/config/lwcConfig.ts

**Comment by muenzpraeger** [comment]
Good catch, fixed with #492
