### ISSUE TITLE
Express is included even if omitted during setup

### ISSUE THREAD

**Issue by paustint** [muenzpraeger/create-lwc-app#487]
### Summary

Choosing `N` to express or explicitly specifying silent options, still includes it in the repo.

`npx create-lwc-app my-app -t standard --yes -o typescript`

(**Bug 2**: I would expect `server.js` to be `server.ts` if I chose to use Typescript in a project and would expect that the required `@types` would have been installed)

### Steps To Reproduce:

1.  `npx create-lwc-app my-app -t standard --yes -o typescript` or choose `N` to express in the non-silent mode
1.  Look in repo and notice that  `scripts/server.js` is created and `compression` `express` `helmet` are installed in package.json

### Expected result

Server file and express should not have been installed

### Actual result

Server file and express were installed

**Comment by muenzpraeger** [comment]
`express` is for adding the files for running a dedicated "API" server. The dependency will always be there, as it's needed for running the `serve` script.

For the similar reason it's not a `ts` file as default. That was previously, and caused more confusion than anything else.
