### ISSUE TITLE
Documentation does not provide much help on getting started

### ISSUE THREAD

**Issue by paustint** [muenzpraeger/create-lwc-app#488]
**What is missing from the application? Please describe.**
I am trying out lwc out for the first time off-platform for a small documentation site I have, and I wanted to share my experience with the repo maintainers in case you were unaware of the developer experience from someone not already experienced with the project.

1. The docs on lwc.dev and in this repo on getting started with `create-lwc-app` don't provide any detail on the options available with the cli.
    - I was able to look at the help, but the examples were very minimal without any additional description
    - e.x.: I want to use typescript - eventually I found this was a standard supported option, but I did not find any documentation and so I just have to spend time trying things and attempting to figuring it all out.
1. When I choose the typescript flag, the generated `jsconfig.json` file should actually be `tsconfig.json` to allow for auto-import intellisense from the IDE
1. It would be great if there was an example showing custom webpack and rollup files to show how to customize these. I eventually figured out how to use a custom webpack config, but it took a bit of trial and error and searching through the code-base to learn how my webpack file would be handled with the lwc base webpack config (e.x. they are merged)
1. Running `npx create-lwc-app --help` showed the following example: `yarn init lwc-app my-app -o yarn,typescript`, but when I ran this combined with `--type standard` I got an error saying that silent options flag must be included to use the options flag. The examples in the cli help should be valid.

I was able to get up and running eventually, but initially I was frustrated and had to look through the code base and perform trial and error to see what the outcome of various CLI commands would be.

**Describe the solution you'd like**
1. Documentation on the CLI options with additional context and information for each of the options
1. Documentation on using a custom webpack/rollup configuration file
1. Better types here https://github.com/salesforce/lwc (e.x. `bundler: string` could maybe be `bundler: 'webpack' | 'rollup'`) - since this is not documented specifically, it would have been helpful for my while I was using the typescript definition as my documentation.

**Comment by muenzpraeger** [comment]
@paustint Sorry for the delayed response, and thank you for the detailed issues. Sorry that you had to run into these things. I didn't had time to work on the README. Till now. The latest changes are merged in, LMK what you think.

RE: `tsconfig.json` - that's not needed. A `jsconfig.json` is basically a `tsconfig.json` with `allowJs:true`. VS Code should pick it up automatically.
