### ISSUE TITLE
Support the new module resolution functionality in 1.4.0-alpha3

### ISSUE THREAD

**Issue by blittle** [muenzpraeger/create-lwc-app#506]
**What is missing from the application? Please describe.**
It looks like lwc-services is broken with the new version of 1.4.0-alpha3. When upgrade the underlying dependency, I get the error: `(node:89702) TypeError Plugin: lwc-services: resolveModules is not a function`

**Describe the solution you'd like**
It would be great for lwc-services to support the new version of module resolution. Module resolution is a big deal for the open source version of LWC.

**Describe alternatives you've considered**
The alternative would be to _not_ upgrade to the latest. The current module resolution has a number of bugs (https://github.com/salesforce/lwc/pull/1608) and isn't well documented.

**Additional context**
I'm happy to submit a PR fixing this if you'd like!

**Comment by muenzpraeger** [comment]
Thanks for opening the issue. It is already on my to do list, and I am waiting till that change lands in the `next` tagged release on npm.

**Comment by muenzpraeger** [comment]
Implemented in `lwc-services@2.0.6-beta.4`.

Now waiting that [this PR](https://github.com/salesforce/lwc-test/pull/74) lands for Jest, and we're good to go.
