### ISSUE TITLE
Eject from lwc-create-app

### ISSUE THREAD

**Issue by mjyocca** [muenzpraeger/create-lwc-app#51]
**What is missing from the application? Please describe.**
A way to properly eject from the main scaffolding project. 

**Describe the solution you'd like**
`lwc-services eject `

**Describe alternatives you've considered**
Forking the repo. 

**Additional context**
I'm sure this is on its way or in the roadmap with the note, `It's not a full "eject" out of this tool. Yet.`, next to `lwc-services sniff` command.

**Comment by muenzpraeger** [comment]
Someone is reading the command notes... yay! ;-)

Besides that, @mjyocca, yes, it's on the roadmap. And eventually it'll supersede the `sniff` command. It wasn't implemented yet, as some things re: correctly packaging everything are still in flux, and as new features/packages are on it's way.

It'll be some time out, but it's coming.

**Comment by mjyocca** [comment]
@muenzpraeger Awesome to hear! Understandable why it's not in yet. In the meantime if one needs to hook into the webpack build process do you recommend just forking the project for now?

**Comment by muenzpraeger** [comment]
Does passing a custom `webpack.config.js` not suffice? That gets merged with the built-in.

Happy to learn more about the use case.

**Comment by mjyocca** [comment]
Oh! I didn't realize they were merged together with `webpack-merge`. Yeah that does work for the use case I have right now. But I can see where a proper eject would be needed down the road.

**Comment by muenzpraeger** [comment]
Yup, that‘s coming at some point.

And yes, for these kind of requests I added `webpack-merge` from the very beginning. ;-)

**Comment by mjyocca** [comment]
Well good thinking on your part! I'll close this issue since its planned and on the way.

**Comment by muenzpraeger** [comment]
I leave it open. Better tracking. ;-)

**Comment by pmdartus** [comment]
@muenzpraeger I am wondering what would use cases where you want to eject the project?
IMHO, when a project gets ejected you lose all capabilities of updates. Ideally, we should make the `lwc-service` package for consumers to hook themselves into the build step without having to eject.

**Comment by muenzpraeger** [comment]
I see some reason to eject. At least when people want to use custom `webpack` builds. Some plugins don't play well with others, or need to be added in a certain order.

Having said that we should always strive to provide a capability that an `eject` is the last resort for a dev. ;-)
