### ISSUE TITLE
Add ability to customize the relative path of bundle script tags in index.html

### ISSUE THREAD

**Issue by DeadlySemiColon** [muenzpraeger/create-lwc-app#543]
In most of my use cases I have my lwc app in a sub directory of my express apps public folder like so:
content (public dir) --> lwc --> [lwc dist contents]

Which means each time I bundle my lwc app I have to update the relative paths of the script tags.
**Example:** `<script src="lwc/0.app.js"></script>`

Or alternatively I modify the webpack-builder.js file in "node_modules/lwc-services" **(naughty I know, but it works)**

I would love the ability to specify the public path of the bundle in the lwc-services.config.js file.

**Comment by muenzpraeger** [comment]
Have you considered using a custom `webpack.config.js` (with the `-w` parameter on `build` and `watch` commands). The config gets merged into the built-in one.

**Comment by DeadlySemiColon** [comment]
I hadn't considered that approach.

To be quite honest I am not well versed in webpack so maybe it's an obvious approach to some, but how would I target the appropriate part of your config with my own?

I can see your code allows for a "customConfig" parameter, but how would you structure the custom configuration to modify the public path property of your config? Or am I looking at it from the wrong approach?

**Comment by muenzpraeger** [comment]
A webpack config in it's simplest form is just a JS object. The merge works like an `Object.assign`, basically, using [this npm package](https://www.npmjs.com/package/webpack-merge).

Here's what you need in your own `webpack.config.js` file.

```javascript
module.exports = {
     output: {
         publicPath: '/lwc-or-whatever-you-want-as-path'
    }
}
```

And then you can just use it by referencing the relative file path to the root in your build scripts with the `-w` parameter (i. e. `lwc-services build -w webpack.config.js`).

**Comment by DeadlySemiColon** [comment]
That worked like a dream! Thanks so much for the assist.
