### ISSUE TITLE
Adding custom environment variables to a build.

### ISSUE THREAD

**Issue by adrian-cg** [muenzpraeger/create-lwc-app#544]
**What is missing from the application? Please describe.**
A way to define some environment variables to be included in the build. Similar to create-react-app
https://create-react-app.dev/docs/adding-custom-environment-variables/

The use case here is that I have an app with an express server. The dev server running in watch mode proxies requests (so I can do fetch('/api/v1/endpoint')), but when doing npm build && npm serve then these requests fail since there are two different instances of express running on different port.

**Describe the solution you'd like**
Being able to leverage the API_HOST and API_PORT environment variables to let my client know the url for my api server.

**Describe alternatives you've considered**
Having the scripts/server.js express server forward those requests? to the correct place? I'm not really sure, that feels hacky. Currently exploring DefinePlugin in a custom webpack config.

UPDATE:
I got it working with the 'dotenv-webpack' plugin. I created a webpack.config.js in my project root

```
const Dotenv = require('dotenv-webpack');

module.exports = {
    plugins: [
        new Dotenv()
    ]
}
```

then I updated the lwc scripts in package.json and added `-w webpack.config.js` so that it merges my custom webpack config file (at least I think that's what it does)

It's really nice to be able to tweak the webpack config without having to eject. Thanks for that feature!

**Comment by muenzpraeger** [comment]
Thanks for opening the issue - that's what I was thinking first, using a dedicated webpack plugin (like dotenv or [string-replace-loader](https://www.npmjs.com/package/string-replace-loader)). Let me know if you find other things that you consider to be useful! Cheers!
