### ISSUE TITLE
Watcher requires Hard Reload to see the changes

### ISSUE THREAD

**Issue by ivanovivelin** [muenzpraeger/create-lwc-app#550]
### Summary

Running **npm run watch** should reflect the changes that were made, but to see those I need to hard reload 

### Steps To Reproduce:

1.  Run **npm run watch**
2. Change some of the modules/ components to trigger the watch
3. See if the changes are reflected  [hard reload is required here].  

### Expected result

Should not need to hard reload to see the changes.

### Actual result

Hard reload is required to see the changes.

**Comment by muenzpraeger** [comment]
What's the namespace of your modules (aka: parent folder name)?

**Comment by ivanovivelin** [comment]
@muenzpraeger the project structure looks like this : 

<img width="535" alt="Screenshot 2020-04-20 at 09 07 15" src="https://user-images.githubusercontent.com/22252962/79723696-7ed1f780-82e6-11ea-852a-3ba5b0613d8b.png">

I did not really modify anything after I created the app with 

**npx create-lwc-app my-app -t pwa --yes**

**Comment by muenzpraeger** [comment]
Ah, the PWA. Make sure in your browser dev tools that it picks up the changes, as it caches them.

**Comment by ivanovivelin** [comment]
Thanks @muenzpraeger
