### ISSUE TITLE
Support for Electron js https://www.electronjs.org/

### ISSUE THREAD

**Issue by Jerrkawz** [muenzpraeger/create-lwc-app#606]
**What is missing from the application? Please describe.**
An option for generating an electron configuration for the web application so it can be used on the desktop instead of using an express js server and a browser.

**Describe the solution you'd like**
Probably just an additional prompt asking if you would like to use an electron shell.

**Describe alternatives you've considered**
I have a boilerplate project for using LWC and Electron but I would love to see it in this utility

**Additional context**

**Comment by muenzpraeger** [comment]
Great idea. See [here](https://github.com/muenzpraeger/create-lwc-app/blob/master/packages/create-lwc-app/src/generators/createGenerator.ts#L147). 😎

Just need to find some time.

**Comment by Jerrkawz** [comment]
@muenzpraeger Excellent. I checked other issues but didnt see anything. Would you consider adding just electron support or would it have to be via cordova. If just electron is acceptable at least in the short term then I could potentially submit a PR but i feel like using cordova may add additional complexity that I don't have time to do

**Comment by muenzpraeger** [comment]
Yeah, good question. My original thinking was around to leverage just the Cordova CLI, as it allows to build different destinations. Pretty much how the [Framework7 CLI](https://github.com/framework7io/framework7-cli/blob/master/create/templates/create-cordova.js#L22) does it. Another option that I was looking in was to scaffold something with `electron-builder`.

What would you think about the latter option (in general)?

**Comment by Jerrkawz** [comment]
I see, either of those options seems pretty simple although it adds depencies for something that seems relatively simple. You just need an electron config and a simple script to fire up the shell, very similar to the boilerplate for an express server. I haven
t looked at the code yet, what do you do to create the express server? Call into another utility or just copy the boilerplate from somewhere?
