### ISSUE TITLE
Add support multi page application

### ISSUE THREAD

**Issue by pmdartus** [muenzpraeger/create-lwc-app#611]
> Originally posted at https://github.com/salesforce/lwc/issues/1915

We are easily able to setup LWC application using https://lwc.dev/. But as per given example, we are only able to setup Single Page Application. Our client needs a Multiple Page Website using this framework. How to do that?

We have lwc-services.config.js file. In that file also we are allowed to give only 1 sourceDir. This way, LWC OSS only supporting Single Page Application. I can see we have a default Client folder in application. In that we have index.html / index.js files. If i want different files for other pages like "login.html", "about.html", "myaccount.html", then it does not work. I tried different ways, but what i see is that only index.html/index.js works. Any other files failed to load or work.

**Comment by aslambari** [comment]
@muenzpraeger for further communication here.
We are using this command for making app
npx create-lwc-app myapp

In this I do not find option for supply custom configuration for webpack. May be I am missing something. You suggested to use -w with build. I also tried this:

npm lwc-services build -w custom.config.js

but no luck.

**Comment by muenzpraeger** [comment]
It’s documented [here](https://github.com/muenzpraeger/create-lwc-app#lwc-services-build) in the README of the project.

**Comment by aslambari** [comment]
@muenzpraeger do we have a sample custom.config.js example for LWC. Because when I try this, I am keep getting this error:

Module not found: Can't resolve 'my/app'

My custom.config.js

module.exports = {
  entry: {
    index: './src/client/index.js',
	login: './src/login/index.js'
  },
  output:{
        filename: '[name].js',
        path: __dirname + '/build',
        chunkFilename: '[id].[chunkhash].js'
    }
};

**Comment by muenzpraeger** [comment]
I see the issue now - you'd need the new module resolution mechanism. Sorry for not pointing that out earlier, I thought it was already in 2.0.7

Do this:
- Install `lwc-services@beta` (got released a few weeks ago, go-live as `latest` potentially tomorrow). That one includes the LWC based module resolution.
- Add a `lwc.config.json` to the root of your project with this content:

```
{
    "modules": [
        {
            "dir": "src/modules"
        }
    ]
}
```

Basically what happened is that the LWC team provided a mechanism to configure _n_ configs where you're storing your module directories. This supersedes the previous config via `lwc-services.config.js`.

To read more about what options you have for the module resolution I recommend to check out the [RFC](https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution#directorymodulerecord).

**Comment by aslambari** [comment]
@muenzpraeger I will give it a try once latest build available for lwc-services.
However i tried with @beta. The error was not coming regarding my/app. But still only index page working, no other entry working. Only single entry working for me still.

**Comment by muenzpraeger** [comment]
@aslambari There are a couple of things that I think need clarification. An entry point is the generated JS. If you want to generate multiple HTML files, you've to configure that using the options of the `html-webpack-plugin` (docs [here](https://github.com/jantimon/html-webpack-plugin#options)) in your custom `webpack.config.js`.

I recommend to peak into the used webpack config of `create-lwc-app` (using the `sniff` command), so that you can see what's shipped as default, and what you need to add/override using custom configs.
