### ISSUE TITLE
Error only on Windows 10

### ISSUE THREAD

**Issue by rkedia72** [muenzpraeger/create-lwc-app#619]
### Summary

Encounter error on windows 10 when following trailhead "Build Your First Application with Lightning Web Components Open Source". This error does not occur on Mac OS.

Error message:

ERROR in ./src/client/index.js
Module not found: Error: Can't resolve 'my/app' in 'C:\sf\repos\conference-app\src\client'
 @ ./src/client/index.js 3:0-27 5:6-11
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./src/client/index.js
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'

### Steps To Reproduce:

1.  npx create-lwc-app conference-app --yes -o edge,express
1.  cd conference-app
1. npm run watch
### Expected result
No errors should be encountered
### Actual result
The following errors occurred:
ERROR in ./src/client/index.js
Module not found: Error: Can't resolve 'my/app' in 'C:\sf\repos\conference-app\src\client'
 @ ./src/client/index.js 3:0-27 5:6-11
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./src/client/index.js
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
@rkedia72 That looks like a permission issue on the affected machine to me.

**Comment by HarmonJared55** [comment]
@rkedia72 I working on a different project, and ran across this on google. I am experiencing the same issue. I am forced to use a remote desktop and am wondering if you are as well? That might be the cause of the issue in some way.

**Comment by rkedia72** [comment]
@HarmonJared55  I am not using remote desktop.

**Comment by rkedia72** [comment]
I tried it on my personal laptop. It worked without errors. So it seems like an issue with permissions or anti virus software.
