### ISSUE TITLE
Do Compat Builds work?

### ISSUE THREAD

**Issue by Renji-XD** [muenzpraeger/create-lwc-app#64]
Not sure if just miss something but i think if you set the compat property to true via lwcConfig it has no Effect.

It looks like you are using the transform Method of the Compiler Package - which when I compare it against the exported compiler function does not care about any compact flag (at least i saw nowhere any condition which would access it). Also if i inspect the code which was build for production i still seeing stuff like arrow functions, await statements, spread operator etc.

Not sure if that is related (i did not found explicit documentation about it) and the synthetic shadow would be applied if compat works. But right now page loads immediately fail in ie / edge for me due to the missing shadow dom support (and no loaded synthetic shadow polyfill I guess). If i manually include the shadow.js in the index.html it works for Edge - IE is still failing due to the missing ES6 Support (and not applied transforms)

So Question is if that is a bug or if I just forgot about sth.

**Comment by muenzpraeger** [comment]
The `mode` flag isn't respected, it only works if you've set `mode=production` in your local environment.

Should be fixed in the upcoming release.
