### ISSUE TITLE
[lwc.config.json]  npm property not being processed 

### ISSUE THREAD

**Issue by gonzalocordero** [muenzpraeger/create-lwc-app#653]
1. Having the following configuration:

```
{
    "modules": [
        {
            "dir": "src/client/modules",
            "npm": "lightning-base-components"
        }
    ]
}
```

The npm property is not getting processed, when attempting to import `<lightning-*>` it's not able to find it. 

My assumption was that the compiler would look for that file and process it accordingly, but it's not being the case. However, The same configuration with the the raw LWC plugin works fine. (that is not using lwc-create-app but just a vanilla app with the lwc-rollup-plugin)

My setup:
- npx create-app with rollup as my bundler.

**Comment by armandoisaac** [comment]
@gonzalocordero , lwc.config.js expects either npm or dir property per object of the array:

```{
  "modules": [
    {
      "npm": "your-npm-package"
    },
    {
      "dir": "src/modules"
    }
  ],
  "expose": [
   "yourNamespace/yourComponentName"
  ]
}```

Your NPM package should have it's own `lwc.config.js` file with a `dir` configuration and should also expose all components you want to use on client projects.

**Comment by muenzpraeger** [comment]
What @armandoisaac said, see the spec [here](https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution#detailed-design).
