### ISSUE TITLE
TypeError: undefined is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

### ISSUE THREAD

**Issue by DougMidgley** [muenzpraeger/create-lwc-app#655]
### Summary

When running LWC using watch, everything runs as expected, but when doing Build for production we get an error which suggests an issue with code, but due to bundling is not exactly easy to understand what is causing it.

### Steps To Reproduce:

1.  Execute 'npm run watch'
1.  Open devserver version
1.  Runs correctly
1.  Push to Heroku
1.  Open public URL
1.  Error thrown in console

### Expected result

Watch and Build execute the same

### Actual result

Build throws error while Watch does not

### Additional information

It seems like some reference is missing, for sure this issue does not occur in dev. All modules have extends LightningElement.

Error in console
`0.app.js:9 Uncaught (in promise) TypeError: undefined is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.
    at Ir (0.app.js:9)
    at 0.app.js:9
    at Object.create (0.app.js:9)
    at qt (0.app.js:9)
    at 0.app.js:9
    at mi (0.app.js:9)
    at Ur (0.app.js:9)
    at Object.update (0.app.js:9)
    at Gt (0.app.js:9)
    at qt (0.app.js:9)`

lwc-services.config.js
`const webpackConfig = {
    resources: [{ from: 'src/client/resources', to: 'dist/resources/' }],
    sourceDir: './src/client'
};
module.exports = webpackConfig;
`

scripts from package.json
`"scripts": {
        "build": "lwc-services build",
        "build:development": "lwc-services build -m development",
        "build:cert": "cd certificates && buildCert.bat",
        "lint": "eslint ./src/**/*.js",
        "prettier": "prettier --write \"**/*.{css,html,js,json,md,ts,yaml,yml}\"",
        "prettier:verify": "prettier --list-different \"**/*.{css,html,js,json,md,ts,yaml,yml}\"",
        "serve": "run-p serve:client serve:api",
        "serve:api": "node src/server/api.js",
        "serve:client": "node scripts/server.js",
        "test:unit": "lwc-services test:unit",
        "test:unit:coverage": "lwc-services test:unit --coverage",
        "test:unit:debug": "lwc-services test:unit --debug",
        "test:unit:watch": "lwc-services test:unit --watch",
        "watch": "run-p watch:client watch:server",
        "watch:client": "lwc-services watch",
        "watch:server": "nodemon",
        "start": "node src/server/api.js"
    }`

**Comment by muenzpraeger** [comment]
Hey - that looks like something hasn't been resolved correctly, as its "undefined". Do you get the same issue when running the build locally?

**Comment by muenzpraeger** [comment]
Not sure how much I can help here, as the build seems to work.

**Comment by muenzpraeger** [comment]
Let me know if there is anything to follow-up on, @DougMidgley. Otherwise I'll close this in a few days.

**Comment by DougMidgley** [comment]
Hi @muenzpraeger All seems ok now, no reason i could find why it was not working but refreshed everything and made some other unconnected changes and things were ok. Potentially a patch fixed it somewhere.
