### ISSUE TITLE
PWA not giving the Install option when running the "serve" command

### ISSUE THREAD

**Issue by adityanaag3** [muenzpraeger/create-lwc-app#681]
### Summary
When running the PWA created with this tool using the `serve` script, the "Install" option that Chrome gives is not available. However, the Install option is available when running the app using the `watch` script.

### Steps To Reproduce:

1.  Run the app using `npm run watch`. Open localhost:3001 in Chrome and observe that the Install option appears in the address bar and Chrome Menu.
1.  Build the app using `npm run build` and then run `npm run serve`. Observe that the Install option doesn't appear.

### Expected result
The Install option must appear in the Chrome address bar and menu bar.

### Actual result
The Install option doesn't appear in the Chrome address bar and menu bar.

### Additional information

Upon inspection, it turns out that Chrome isn't able to run the script to register the service worker
![image](https://user-images.githubusercontent.com/11162785/92588776-2613f300-f2b7-11ea-9c18-11de43b98d66.png)

The fix I applied was to include the below code before `app.use(express.static(DIST_DIR));` in the `scripts/server.js` file

```
app.use(function(req, res, next) {
    res.setHeader("Content-Security-Policy", "script-src 'self' 'unsafe-inline'");
    return next();
});
```

Wondering if this is the right fix, or is there some way to do this better. If this is the fix, please add this to the boilerplate code generated by the tool.

**Comment by muenzpraeger** [comment]
This would be the right implementation. It is also correct that it is not included in `scripts/server.js`, as this decision for a production implementation is the responsibility of each developer.
