### ISSUE TITLE
Update `lwc-services` to use Webpack v5

### ISSUE THREAD

**Issue by julianduque** [muenzpraeger/create-lwc-app#696]
**What is missing from the application? Please describe.**

Webpack 5 comes with a new JavaScript parser and support for new ECMAScript features that can improve the developer experience with LWC-OSS

**Describe the solution you'd like**

Use Webpack 5 instead of Webpack 4

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by muenzpraeger** [comment]
Available now with v3.0.0 🎉
