### ISSUE TITLE
Support Multipage builds

### ISSUE THREAD

**Issue by DougMidgley** [muenzpraeger/create-lwc-app#711]
**What is missing from the application? Please describe.**
Ability to build multiple pages in application to avoid bloat from unneeded dependencies. https://medium.com/anuix/set-multiple-outputs-in-webpack-aa1e16da9b56 for example covers this logic.  https://github.com/muenzpraeger/create-lwc-app/issues/587# also seems to request it.  

**Describe the solution you'd like**
Ideally we should be able to pass in multiple webpack configs to run builds for each page independently.  Alternatively, we could skip adding index.html when any named entry points are called index (essentially an override).

**Describe alternatives you've considered**
- HtmlWebpackPlugin - Right now we can use the HtmlWebpackPlugin but this still creates an index file ( with all entry source dependencies). We then need to run jobs to go and clean this up which is rather unideal.
- SPA - accept page bloat and use a single page app with custom routing logic. Skipping this due to no OOTB routing logic in LWC
- Run multiple commands against multiple webpack.config.js files - Use package.json scripts to build each page one after the other. Down side here being that it would also run all the other common scripts (like copy resources) and would not created shared bundles (for example base components lib).

**Additional context**
I can certainly see the complexity in doing this, but I feel it would help provide a more real-world support for Open Source LWC. Happy to try and help with a PR but not exactly my specialty.

**Comment by muenzpraeger** [comment]
As mentioned in #533 `lwc-services` has the prescribed way with a default webpack configuration.

If you want to customize as described you would have to use, as you mentioned, custom webpack configurations. Or you eject from the default configuration, and run a full custom webpack config (similar to `create-react-app`). 

At the end this project is meant to be a starter project with sensible and standard defaults, but it can't get all the different variations.

**Comment by DougMidgley** [comment]
Hey @muenzpraeger was inspired to do exactly that, but still keep hitting the challenge of resolution of  LWC modules, notably, without referencing 
lwc-services/lib/utils/webpack/module-resolver.js and lwc-services/lib/utils/webpack/module-loader.js that you have in the lwc-service module there is no 'packaged' way to manage the dependencies :(  Any hints/tips here?

**Comment by muenzpraeger** [comment]
@DougMidgley I release today [this on npm](https://www.npmjs.com/package/lwc-webpack-plugin). LMK if if solves your issue. ;-)

**Comment by DougMidgley** [comment]
Works a charm :) https://github.com/Accenture/sfmc-customapp
