### ISSUE TITLE
Include component scaffolding

### ISSUE THREAD

**Issue by jmpisson** [muenzpraeger/create-lwc-app#717]
**What is missing from the application? Please describe.**
Although `create-lwc-app` performs great on creating a new app from scratch, there is no actually a method to scaffold a new component from scratch. Usually, I found myself copying a component folder and renaming every file in order to introduce a new component on the project.

**Describe the solution you'd like**
The project shoud have a new command or method for scaffold the different component types we are used to develop on LWC projects (including ES6 and CSS modules).

Maybe, including the usage of `mustache` templates would allow end users to create specific templates for each project.

**Describe alternatives you've considered**
Probably, the best option IMO is to develop a new command on `lwc-services`, as this functionality will be usually tied to this app.

**Additional context**
I have developed a new oclif command on `lwc-services` that creates a new component within the `src`folder specified on `lwc-services.config.js` and tries to replicate the same name logic of SFDX.

**Comment by muenzpraeger** [comment]
I was considering that. Although I'd be more a fan to have that [integrated](https://github.com/forcedotcom/salesforcedx-vscode) into VS Code.

**Comment by jmpisson** [comment]
Hi @muenzpraeger! Sorry I have been quite busy at work lately, thank you for your answer!

That would be a great a idea, but I was not sure if there any kind of project for this. Anyway I would be happy to help there

**Comment by muenzpraeger** [comment]
I suggest you open an issue on the above repo, and offer there your help. That would be the best place, and they can advice you further.
