### ISSUE TITLE
CSP errors when running "npm run serve" but not when running "npm run watch"

### ISSUE THREAD

**Issue by eltoroit** [muenzpraeger/create-lwc-app#735]
### Summary

I am building a component that embeds a YouTube video, but I am getting a CSP error if I "serve it" (npm run serve) but not if I "watch it" (npm run watch). I believe there is something on the JavaScript that gets created when the project is "built" (npm run build) that causes this issue.

### Steps To Reproduce:

With a component that embeds a YouTube video via an iframe, execute these statements

1.  npm run build
1.  npm run serve

Open the browser and view the iframe content is blocked, but if you do this

1. npm run watch

The videos get properly shown.

### Expected result

The videos should not be blocked

### Actual result

The videos get blocked

### Additional information

This is how I am embedding YouTube

```
<iframe src={url} frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

I am also adding this line to the index.html file

```
<meta http-equiv="Content-Security-Policy" content="frame-src 'self' https://www.youtube.com" />
```

**Comment by muenzpraeger** [comment]
That's the default `helmet` configuration. You can modify as needed.

https://github.com/helmetjs/helmet

**Comment by eltoroit** [comment]
Thanks, I updated `scripts/server.js` and changed this line:

```
app.use(helmet());
```

To this code:

```
app.use(
	helmet({
		contentSecurityPolicy: false
	})
);
```

And it worked, thanks!
