### ISSUE TITLE
LWC Services no longer honoring lwcStylesheetConfig on lwc.services.json

### ISSUE THREAD

**Issue by jmpisson** [muenzpraeger/create-lwc-app#736]
### Summary

It looks that `lwc-services` does not honor lwcStylesheetConfig property inside `lwc-services.config.js`.

### Steps To Reproduce:

1.  Use create `create-lwc-app` to scaffold a review app
1.  Add the following to `lwc-services.config.json` 
````
// Find the full example of all available configuration options at
// https://github.com/muenzpraeger/create-lwc-app/blob/main/packages/lwc-services/example/lwc-services.config.js
module.exports = {
    resources: [
        { from: 'src/client/resources/**', to: 'dist/resources/' },

        { from: 'src/client/index.html', to: 'dist/' }
    ],

    sourceDir: './src/client',
    
    lwcCompilerStylesheetConfig: {
        customProperties: { allowDefinition: true }
    },
};
````
3. Include a CSS property `--my-prop` inside `greetings.css`.

### Expected result

The app compiles as expected.
### Actual result

LWC Compile throws an exception 'Invalid definition of custom property "--my-prop"'.

### Additional information

Debugging code, it looks that LWC Webpack Plugin does not passs to the compiler any configuration aside the module resolving.

**Comment by muenzpraeger** [comment]
Good catch. Will take care of it today.

**Comment by msrivastav13** [comment]
ran into this today!!  Tracked the commit that created the issue to this [one](https://github.com/muenzpraeger/create-lwc-app/pull/712/files)

**Comment by bilal-elchami** [comment]
Same here! Got the exception today! When do you think the fix will be merged?

**Comment by jmpisson** [comment]
Hi there! As a workaround, I defined my custom properties on root element, within `index.html` file. This works if you only need to define new custom properties which are global to the components.

It's something like this code:

index.html
`<html>
    <link rel="stylesheet" scr="/path/to/slds"< />
    <style>
        --sds-c-button-brand-color-background: #BB00FF;
    </style>
</htmL>`
