### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by surajrathod** [muenzpraeger/create-lwc-app#739]
when I try to run the server and client app on Heroku it gives the error
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0.

but locally it works

instead of responding the Json version it response the html version

**Comment by muenzpraeger** [comment]
This looks like an issue with your setup (assuming you're calling an API endpoint). Without further information there's not much I can help here.

**Comment by muenzpraeger** [comment]
Closing b/c of no response
