### ISSUE TITLE
Configure Babel to accept 'declare' syntax for class fields in the LWC build when using typescript

### ISSUE THREAD

**Issue by jmlewis2** [muenzpraeger/create-lwc-app#762]
**What is missing from the application? Please describe.**
This is another small compilation problem in the LWC build whereby typescript syntax that would be accepted by tsc is rejected by Babel. The 'declare' syntax for class fields is not accepted by Babel unless the allowDeclareFields option is set on @babel/preset-typescript. (It seems this will be enabled by default in Babel 8.)

**Describe the solution you'd like**
Amend lwc-webpack-plugin to set allowDeclareFields:true on @babel/preset-typescript in the transform for typescript files. 

**Describe alternatives you've considered**
A quick fix is to patch node_modules/lwc-webpack-plugin/dist/loader.js, amending the presets array for the typescript transform:
      presets: [
                    [
                        require.resolve('@babel/preset-typescript'),
                        {
                            allowDeclareFields: true
                        }
                    ]
            ]

**Comment by muenzpraeger** [comment]
New version just released
