### ISSUE TITLE
Unable to enable CSS custom properties

### ISSUE THREAD

**Issue by blittle** [muenzpraeger/create-lwc-app#763]
### Summary

The `lwcCompilerStylesheetConfig` is not propagated to the `rollupConfig`: 

### Steps To Reproduce:

1.  Add `lwcCompilerStylesheetConfig` to your `lwc-services.config.js` as defined here: https://github.com/muenzpraeger/create-lwc-app/blob/main/packages/lwc-services/example/lwc-services.config.js#L43
1.  Compile the project

### Expected result

The stylesheet config is passed to the LWC compiler and I can enable CSS custom properties. 

### Actual result

The stylesheet config is not passed and it is impossible to enable CSS custom properties

### Additional information

I think this can easily be resolved by adding:

```js
stylesheetConfig: lwcConfig.lwcCompilerStylesheetConfig || {}
```

to https://github.com/muenzpraeger/create-lwc-app/blob/main/packages/lwc-services/src/config/rollup.config.js#L78

I'm happy to submit a PR if you'd like! Thank you!

**Comment by muenzpraeger** [comment]
Great catch! Fixing this in the Friday release.
