### ISSUE TITLE
[lwc-services] build command ignores --webpack parameter

### ISSUE THREAD

**Issue by STUkh** [muenzpraeger/create-lwc-app#783]
### Summary

`lwc-services buld --bundler=webpack --webpack=./webpack.dev.js` resulting invalid config that works unexpectedly.
Looks like it trying build on top of `webpack.dev.js`without merge.

Same options combination works correctly for `lwc-services watch`

### Steps To Reproduce:

1.  Create custom webpack develop config.
1.  Run `lwc-services buld --bundler=webpack --webpack=./webpack.dev.js`

### Expected result

Returns merged config of default built-in with custom that provided from cli parameter

### Actual result

Unexpected build errors. Looks like resulting config totally replaces with custom instead of merge.

### Additional information

Same options with `lwc-services watch` works correct

From code perspective fix should be very simple. If you need any help with PR just let me know.

**Comment by muenzpraeger** [comment]
Just released `3.0.3`, which should fix that.
