### ISSUE TITLE
Custom HtmlWebpackPlugin config support for lwc-services

### ISSUE THREAD

**Issue by ninoish** [muenzpraeger/create-lwc-app#814]
**What is missing from the application? Please describe.**
A clear and concise description of what the problem is. Ex. I'd like to see an implementation of [...]

When adding HtmlWebpackPlugin configuration to a custom `webpack.config.js` file and running build with `-w` option, it causes a conflict because `webpack-merge` might not be working as expected. I found that there are **two HtmlWebpackPlugin instances after merge** which causes error `Conflict: Multiple assets emit different content to the same filename index.html`.

Below is the result of console.log just after merge in [here](https://github.com/muenzpraeger/create-lwc-app/blob/77dff848937a2d4c44f994789e16f05df271c5b2/packages/lwc-services/src/commands/build.ts#L132).

```
[
  DefinePlugin { definitions: { 'process.env.NODE_ENV': undefined } },
  HtmlWebpackPlugin {
    userOptions: {
      template: '/path/to/src/index.html',
      minify: [Object]
    },
    version: 5
  },
  Plugin {
    config: {
      stylesheetConfig: {},
      outputConfig: [Object],
      experimentalDynamicComponent: {}
    }
  },
  CopyPlugin { patterns: [ [Object], [Object] ], options: {} },
  ErrorOverlayPlugin {},
  HtmlWebpackPlugin {
    userOptions: {
      minify: [Object]
    },
    version: 5
  }
]
```

I see this behaviour after lwc-service@v3. Not sure if this is lwc-service or webpack-merge issue since it has changed the way it merges custom webpack configs. 

Am I missing something? If true, any guide is grateful.
Here is my webpack.config.js for my custom build.
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  plugins: [
    new HtmlWebpackPlugin({
      minify: {
        removeComments: false
      }
    })
  ]
};

```

Thank you for the great tool.

**Comment by muenzpraeger** [comment]
If it worked before it's potentially a `webpack-merge` issue. I used before the `smart` merge option, which was removed with `webpack-merge@5`. Not much I can do there.

The custom webpack config was really meant to add additional plugins/functionality beyond what is built-in, as this is also just a "starter" project. As you want to override/extend I recommend using a barebones `webpack` or `rollup` project, instead of overriding. That would give you also way more flexibility.
