### ISSUE TITLE
Add ability to mock LWC imports

### ISSUE THREAD

**Issue by gamedevsam** [muenzpraeger/create-lwc-app#828]
**What is missing from the application? Please describe.**

There currently isn't a way to mock LWC component imports. This is important because I'm using [lightning-base-components](https://www.npmjs.com/package/lightning-base-components), and without resolving their stubs, components fail to build when running Jest tests.

**Describe the solution you'd like**

I should be able to provide a config that maps namespaces to a npm directory containing stubs of LWC components, ex:

```js
// in lwc-services.config.json:

module.exports = {
    lwcResolveNamespace: {
        lightning: 'node_modules/@salesforce/lwc-jest/src/lightning-stubs'
    }
};
```

**Describe alternatives you've considered**

I've had to patch my local installation of lwc-services in order to successfully run unit tests, here is the entirety of the patch (it's a small change):

```
diff --git a/node_modules/lwc-services/lib/utils/resolver.js b/node_modules/lwc-services/lib/utils/resolver.js
index dec316f..f39591f 100644
--- a/node_modules/lwc-services/lib/utils/resolver.js
+++ b/node_modules/lwc-services/lib/utils/resolver.js
@@ -42,6 +42,14 @@ module.exports = function (modulePath, options) {
     if (isValidModuleName(modulePath)) {
         const { modulesDir } = getProjectInfo();
         const { ns, name } = getInfoFromId(modulePath);
+        if (ns === 'lightning') {
+            const p = path.join('node_modules/@salesforce/lwc-jest/src/lightning-stubs', name);
+            if (fs.existsSync(p)) {
+                return path.join(p, `${name}.js`);
+            } else {
+                throw Error(`Failed to find mock lightning component for '${modulePath}'`)
+            }
+        }
         try {
             const mod = lwcModuleResolver.resolveModule(modulePath, process.cwd());
             return mod.entry;
```

**Additional context**

I'm using Webpack for bundling.

**Comment by muenzpraeger** [comment]
Thanks for opening the issue.

The module resolver is not in the business of resolving stubs. For that you would have to configure Jest, like it is configured in [this example](https://github.com/trailheadapps/lwc-recipes-oss/blob/master/jest.config.js#L12-L14) for the UI namespace.

**Comment by gamedevsam** [comment]
Fantastic, thank you very much for the advice, I've eliminated my patch and everything is working properly with the addition of this line to the moduleNameMapper:

`'^lightning/(.+)$': '<rootDir>/node_modules/@salesforce/lwc-jest/src/lightning-stubs/$1/$1'`
