### ISSUE TITLE
Missing peer dependencies

### ISSUE THREAD

**Issue by sf-maps** [muenzpraeger/create-lwc-app#835]
### Summary

It appears the plugin has a hard dependency on the `@lwc/engine` and `@lwc/wire-service` packages. However, those packages do not appear to be defined as dependencies. It also appears none of the existing dependencies have dependencies on those packages either.

In short, the plugin will not work unless the above peer dependencies are met. However, they are not listed as peer dependencies.

### Steps To Reproduce:

1. Install plugin
2. Run a build script

### Expected result

Successful build

### Actual result

10:14:34  [webpack-cli] Error: Cannot find module '@lwc/engine'

**Comment by muenzpraeger** [comment]
Which plug-in are you referring to? The Typescript plugin for Rollup, or the Webpack plugin?

**Comment by bk-dev** [comment]
The webpack plugin.

**Comment by muenzpraeger** [comment]
Just released v 2.0.0 which fixes that. Note that this version uses v2 of LWC.

If you rely programatically on `@lwc/engine` you've to change it to `@lwc/engine-dom`.
