### ISSUE TITLE
beta version...can't quit watch server running on 3001

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#84]
### Summary
app started in watch with a server won't exit

### Steps To Reproduce:

1. create a new yarn+ts+server project
2. yarn watch
3. open 3001...works great
4. in the terminal, ctrl+c
5. yarn watch (already running)
6. cmd+w the terminal, and the vscode instance

### Expected result
quit when I ctrl+c

### Actual result
it's still running after quitting terminal and vscode

### Additional information
beta-11

**Comment by mshanemc** [comment]
workaround, fyi

$ lsof -i :3001
COMMAND   PID             USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    23172 shane.mclaughlin   24u  IPv4 0x54ce34d71dfd3621      0t0  TCP *:redwood-broker (LISTEN)
$ kill -9 23172

**Comment by muenzpraeger** [comment]
Fixed in latest `beta`. For testing I recommend to create a new project as some changes to the projects `package.json` have been made.
