### ISSUE TITLE
No matching version found for enhanced-resolve@^5.8.0. when running npx create-lwc-app

### ISSUE THREAD

**Issue by FabienTaillon** [muenzpraeger/create-lwc-app#840]
### Summary

I'm trying to run `npx create-lwc-app my-app-name` but the command fails.

### Steps To Reproduce:

1.  run `npx create-lwc-app my-app-name`.
2.  use all default values (anyway whatever values I choose didn't worked)

### Expected result

LWC App is created.

### Actual result

The command fails, and then the project can't be run.

### Additional information

```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: webpack@5.35.0
npm WARN node_modules/webpack
npm WARN   webpack@"^5.21.1" from lwc-services@3.0.4
npm WARN   node_modules/lwc-services
npm WARN     dev lwc-services@"^3.0.4" from the root project
npm WARN   2 more (babel-loader, copy-webpack-plugin)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^4.0.0" from error-overlay-webpack-plugin@0.4.2
npm WARN node_modules/error-overlay-webpack-plugin
npm WARN   error-overlay-webpack-plugin@"0.4.2" from lwc-services@3.0.4
npm WARN   node_modules/lwc-services
npm ERR! code ETARGET
npm ERR! notarget No matching version found for enhanced-resolve@^5.8.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by muenzpraeger** [comment]
Just tried that, and can't reproduce. Can you eventually verify that it's not local to your machine?

**Comment by FabienTaillon** [comment]
Looks like it's only happening on my machine. Any clue of potential cache or global node_modules folder I should try to delete ?
If not just close it as it seems it's just me.

**Comment by muenzpraeger** [comment]
I wonder if you have a custom `.npmrc` config.

**Comment by FabienTaillon** [comment]
Looks like something was wrong under `./Users/me/.npm/_cacache`.
I deleted everything there and now it's working again 🤷🏻‍♂️
Thanks 👍
