### ISSUE TITLE
beta version: sibling ts files in modules don't resolve

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#85]
### Summary

having a module refer to a sibling file in the same module fails with module not found: Error: Can't resolve './siblingFile' in 'path/to/ns/component'

### Steps To Reproduce:

1.  add another ts file to a component in your modules directory that exports a module
2. import than from the "head" module (the one that shares a name with the folder).  Ex: app.ts

### Expected result

exported modules can be imported

### Actual result

Error: Can't resolve './hello' in '/Users/shane.mclaughlin/code/test-lwc-ts/src/client/modules/my/app'

### Additional information

<img width="1365" alt="Screen Shot 2019-09-03 at 10 48 12 AM" src="https://user-images.githubusercontent.com/4261788/64188623-5faa5680-ce38-11e9-9110-66714998360c.png">

**Comment by muenzpraeger** [comment]
Good find. This resolves though. LOL

`import { someStuff } from './hello.ts';`

**Comment by muenzpraeger** [comment]
Fixed in latest `beta`. For testing you can just upgrade `lwc-services` to `1.3.0-beta.13`.
