### ISSUE TITLE
Please implement a --verbose flag (or equivalent) that prints the webpack build configuration

### ISSUE THREAD

**Issue by luminixinc** [muenzpraeger/create-lwc-app#86]
**What is missing from the application? Please describe.**

We need a way to see the final build configuration that is passed to webpack to be able to debug build problems.

Over the course of debugging a LWC web app that makes heavy use of private scope modules, we encountered a number of fairly obtuse build errors.  We would like a way to expose the verbose workings of the `lwc-services` tool, in particular the final webpack build configuration.

**Describe the solution you'd like**

Possibly a `--verbose` flag could be added to the `lwc-services` tool that would expose the final webpack build configuration.

We've gone ahead and implemented this feature in a fork of this repo.  It has helped us debug and solve the build issues we encountered, and now we think it could help other users as well.

We will issue a PR for this feature forthwith.

**Describe alternatives you've considered**

We have not considered alternatives.

**Additional context**

Prior to this flag we would encounter build errors like the following: 

`🆘  Module not found: Error: Can't resolve '@luminix/user/Id' in '/Users/foo/Documents/LWCPlayground/src/modules/c/simpleLWCTest'`

**Comment by muenzpraeger** [comment]
Does the [sniff](https://github.com/muenzpraeger/create-lwc-app/blob/master/README.md#lwc-services-sniff) command help?

**Comment by luminixinc** [comment]
Yes actually that does help, giving us the final `webpack.config.js`.  So you can disregard/reject the PR if desired.

Thank you!

**Comment by muenzpraeger** [comment]
Yeah, `JSON.stringify` does only the basic output. Will fail with circular dependencies. I keep my solution. ;-)

If you got feature requests in the future - don’t hesitate to open issues! Thanks!
