### ISSUE TITLE
Image not display correctly with Electron Production Build

### ISSUE THREAD

**Issue by mokchend** [muenzpraeger/create-lwc-app#875]
### Summary

When use with Electron with the command: yarn build && yarn start, images are not display correctly as a resource

### Steps To Reproduce:

1.  Take the CompositionBasic LWC OSS
2. See screenshot provided  (amy_taylor.jpg)

### Expected result

Image should be displayed correctly

### Actual result

Image do not displayed, missing ressource

### Additional information
IN ELECTRON CONTEXT
![LWC_OSS_Cannot_find_resource_image_2021-05-23_9-56-07](https://user-images.githubusercontent.com/4774588/119252939-18856b80-bbaf-11eb-8f6e-3f464926f57d.png)

IN WEB CONTEXT : same issue, image did not display correctly
![LWCC_OSS_Connot_find_image_ressource_WEB_2021-05-23_10-13-41](https://user-images.githubusercontent.com/4774588/119253176-4b7c2f00-bbb0-11eb-9144-2ab388ea63d2.png)

Output result
⚡⚡⚡⚡⚡  Lightning Web Components ⚡⚡⚡⚡⚡

📦  Starting build process.
🌎  Local server listening: http://localhost:3001
[HPM] Error occurred while trying to proxy request /resources/images/demo/amy_taylor.jpg from localhost:3001 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /resources/images/demo/michael_jones.jpg from localhost:3001 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[

**Comment by muenzpraeger** [comment]
This is not an issue with `create-lwc-app`, but how the images in your source code are set up.

I don't have time for a full repro. My guess is that you'll have to specify the image path relative à la `./resource...` for Elektron, not absolute as it is currently.
