### ISSUE TITLE
beta13: module resolves to src/modules with baseUrl for TS

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/create-lwc-app#88]
### Summary

This may be related to #85, but I'm not sure it is, so creating a separate issue. I've set `"baseUrl": "./src"` so that I can `import { foo } from 'services/toastService';`.

```
Module not found: Could not resolve services/toastService as <full path>\GitHub\testing\src\modules\services\toastService\toastServiceundefined
```

> Notice the `undefined` at the end of the error message also.

### Steps To Reproduce:

1. Create a file like `src/foo.ts`
1. Set baseUrl in your tsconfig.json under `compilerOptions` object.
1. Try to import `foo` inside of a component.

### Expected result

It should resolve the ts file in `src/services/toastService.ts`

### Actual result

It is inserting a `modules` folder after `src` and failing to resolve. `src/modules/services/toastService.ts`

### Additional information

👍 Most other stuff is working.

**Comment by muenzpraeger** [comment]
It's related to #85.

Assignment of `something` works for me.

```
import { LightningElement, track } from 'lwc';
import { something } from '../../../../services/toastService';

export default class App extends LightningElement {
    @track myStuff = something;
}

```

**Comment by muenzpraeger** [comment]
Fixed in latest `beta`. For testing you can just upgrade `lwc-services` to `1.3.0-beta.13`.

**Comment by Templarian** [comment]
Almost fixed. I can reference from the root with `"baseUrl": "./src"` set if I'm outside of the `modules` folder. So things like `import foo from models/foo' works inside of `services/toastService`.

But if I try to access anything from inside of a component file like `models/foo` it's resolving wrong since it's trying to resolve like `src/modules/models/foo`

**Comment by Templarian** [comment]
https://github.com/dividab/tsconfig-paths-webpack-plugin

I think this plugin solves things by letting webpack read the TS config if it finds one.
