### ISSUE TITLE
Custom terminal parameters for lwc-services build or lwc-services watch commands

### ISSUE THREAD

**Issue by zankoav** [muenzpraeger/create-lwc-app#882]
```
    scripts:{
         "my.build": "lwc-services build -m production --bundler=webpack --webpack=./webpack.production.js --customKey1=customValue1 --customKey2=customValue2"
      }
```

How could I add custom parameters and use it in webpack.production.js ?
Please help me to resolve it

**Comment by muenzpraeger** [comment]
There is no option for that. Available options are:

- Use the standalone [lwc-webpack-plugin](https://www.npmjs.com/package/lwc-webpack-plugin)
- Use node env variables to configure your custom build

**Comment by zankoav** [comment]
I want to use native LWC builder with different builds parameters, I have 16 build types with different components
by type. I don't want use 16 webpack.config.js files with almost same settings. 
Have I any chance ?

**Comment by muenzpraeger** [comment]
This would the a perfect use case for using the `lwc-webpack-plugin`, which is linked above.
