### ISSUE TITLE
undefined in lwc-services build

### ISSUE THREAD

**Issue by ajay312** [muenzpraeger/create-lwc-app#887]
⚡⚡⚡⚡⚡  Lightning Web Components ⚡⚡⚡⚡⚡

🔨  Clearing build directory.
⌛  Creating build configuration
🌟  Using custom configuration from webpack.config.js.
📦  Starting build process.
🆘  undefined

How can we debug where it fails in lwc-services build?

**What is missing from the application? Please describe.**
A clear and concise description of what the problem is. Ex. I'd like to see an implementation of [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by muenzpraeger** [comment]
Please fill out the issue template. Otherwise I won't have enough information to be able to give an answer.

**Comment by muenzpraeger** [comment]
Closing b/c of inactivity
