### ISSUE TITLE
npx create-app throws an error

### ISSUE THREAD

**Issue by georgolden** [muenzpraeger/create-lwc-app#888]
### Summary

command `npx create-lwc-app my-app` not working. npm error throws.

### Steps To Reproduce:

1.  have a Linux OS installed on your PC
1.  install node.js v14 LTS
1.  install npm
1.  run command `npx create-lwc-app my-app`

### Expected result

`npx create-lwc-app my-app` should create a simple lwc app

### Actual result

npm error occurs. 

### Additional information
Logs from npm:
```
5376 verbose Linux 5.12.9-arch1-1
5377 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "husky" "prettier" "eslint" "eslint-plugin-inclusive-language" "lwc-services@^3.1.1" "npm-run-all" "--save-dev" "--no-ignore-scripts" "--cache-min" "86400"
5378 verbose node v14.16.0
5379 verbose npm  v7.16.0
5380 error code ETARGET
5381 error notarget No matching version found for @babel/types@^7.14.4.
5382 error notarget In most cases you or one of your dependencies are requesting
5382 error notarget a package version that doesn't exist.
5383 verbose exit 1
```

**Comment by muenzpraeger** [comment]
Is this something that happens reproducible? And/or are you using a custom npm proxy, or are you connecting directly to `npmjs.com`?

The reason I am asking is that the error message `No matching version found for @babel/types@^7.14.4` means that your installation process cannot find that dependency. Which would be weird, as it is [definitely active](https://www.npmjs.com/package/@babel/types?activeTab=versions) with over 5M installs...

**Comment by georgolden** [comment]
I use `npm` from binary package called `npm`. I can install `@babel/types@^7.14.4` manually using `npm install`. This error occurs only if I use `npx create-lwc-app` command. I have used `create-react-app` many times. React app has `@babel/types` in dependencies and I had no problems at all.

**Comment by muenzpraeger** [comment]
@georgolden There's not much I can do, as whatever gets installed via `npx` is coming from `npx`.

I wonder if there's something stale or custom on your setup. Does the same error occur when running `npx create-lwc-app@latest`?

**Comment by georgolden** [comment]
Yes. Should I open an issue in `npx` github? How can I setup lwc-app manually? What are core dependencies?

**Comment by muenzpraeger** [comment]
For a manual install I suggest to checkout the [official installation instructions](https://lwc.dev/guide/install). Besides `create-lwc-app` you'll find there instructions on how to set up a project manually (with Rollup).

If you prefer Webpack over Rollup you also use the [LWC Webpack plugin](https://www.npmjs.com/package/lwc-webpack-plugin).
