### ISSUE TITLE
Adding slds as a CLI parameter

### ISSUE THREAD

**Issue by ashis-kumar-dev** [muenzpraeger/create-lwc-app#895]
**What is missing from the application? Please describe.**
I would like to see an option to include slds directly into the LWC OSS app. Similar to the options typescriprt or rollup, if we can have an option to use slds within the create-lwc-app command, that would install and create the necessary files for slds support in lwc oss app.

**Describe the solution you'd like**
Lets say we add another option to the existing command, npx create-lwc-app my-app --slds

**Describe alternatives you've considered**
Currently I believe we have to set it up manually and define our own component which links to the slds design files (css and icons)

**Additional context**
We might not want the entire slds assets in the production build files. We might need to consider to purge the unused assets somehow.

**Comment by muenzpraeger** [comment]
@ashis-kumar-dev Thanks for opening the issue. `create-lwc-app` is really just about setting up an LWC project, where SLDS is an additional component that is out of scope.

For adding SLDS I recommend to check out the [ecars](https://github.com/trailheadapps/ecars/tree/main/apps/ecars-pwa) application, which shows the necessary steps.
