### ISSUE TITLE
Problem adding ipcRenderer to browser part of generated electron app

### ISSUE THREAD

**Issue by rrcook** [muenzpraeger/create-lwc-app#899]
### Summary

After adding an ipcRenderer require to a base Electron app, I am getting build errors and am not sure how to proceed to fix it through lwc-services

### Steps To Reproduce:

1.  npx create-lwc-app@latest ipctest
Do you want to use the simple setup? No
Package name for npm ipctest
Description My amazing LWC app
Author Richard Cook
Select a package manager npm
Select the type of app you want to create Electron app
Select a bundler Webpack
Use TypeScript or JavaScript JavaScript
Do you want a basic Express API server? (y/N) n
...
cd ipctest
npm run build:development

electron scripts/main.js   

This produces a working Electron app.

2. Add the following line after line 1 in my/app.js
const { ipcRenderer } = require('electron');

3. npm run build:development

### Expected result

I expected a successful build that would let me build out ipcRenderer code.

### Actual result

I get the following output

🆘  Module not found: Error: Can't resolve 'fs' in '/Users/rrc/gitcode/ipctest/node_modules/electron'
Module not found: Error: Can't resolve 'path' in '/Users/rrc/gitcode/ipctest/node_modules/electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipctest@0.0.1 build:development: `lwc-services build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipctest@0.0.1 build:development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rrc/.npm/_logs/2021-08-08T03_20_08_337Z-debug.log

### Additional information

I tried adding fallback settings to lwcWebpackConfig, I got a build to happen but errors appear in the Electron browser window.

macOS Catalina, npm 6.4.13

**Comment by muenzpraeger** [comment]
Unfortunately I can't really help here. Electron seems to want to use `fs`, which is a node server module, that is not available in-browser.

**Comment by rrcook** [comment]
I have it figured out.
I think I was originally looking at older electron tutorials about how to do ipc communication, I got it working when I set up a preload.js and practices around that. 
I've made an example where when you click a button a message is sent from the render window to the main window, then back from the main window to the render window, within the context of lwc-oss.
Code is at [https://github.com/rrcook/letest2](url)
I think this is important in an electron app, please have a look and consider if you can incorporate this, or your own improvements, in to the electron app part of create-lwc-app.
