### ISSUE TITLE
npx create-lwc-app conference-app gets stuck on both mac and windows

### ISSUE THREAD

**Issue by klmazur22** [muenzpraeger/create-lwc-app#902]
Hi,
I'm trying to complete "Build Your First Application with Lightning Web Components Open Source" on trailhead.
As adviced there, I've installed node.js, git and updated npm.
Then I ran "npx create-lwc-app conference-app --yes -o express" command - it started, the first phase ran successfully ("added 56 packages, and audited 57 packages in 934ms found 0 vulnerabilities"), but then it always gets stuck on the same step:
idealTree:error-overlay-webpack-plugin: timing idealTree:node_modules/error-overlay-webpack-plug

![image](https://user-images.githubusercontent.com/52253035/129341774-6c4c393e-2a9f-4fe2-9670-e80bbe35e79a.png)

Terminating the proccess does not help, because not all of the needed files are installed and even command "npm run watch" cannot be run then.

**Comment by muenzpraeger** [comment]
Does it get stuck for longer than 2 minutes? That looks like an npm issue (and eventually an issue with npm7). To check that you should use npm6, and see if that behavior still shows up.

**Comment by klmazur22** [comment]
Yes, more than a few hours. How can I downgrade my npm version? Trailhead advices to use the latest npm version

**Comment by apodraz2** [comment]
Hi, I was having this same problem. I can confirm that downgrading npm solved the issue.

Use this command to install npm6:

npm install -g npm@6

**Comment by klmazur22** [comment]
@apodraz2 Thank you very much, it helped!
