### ISSUE TITLE
lwcCompilerOutput options for Production not respected

### ISSUE THREAD

**Issue by banderson5144** [muenzpraeger/create-lwc-app#903]
I know it is best practice to minify and compact JS resource for a production environment. But I wanted to see the source-map in my Chrome console. However, when I set my `lwcCompilerOutput` to this:

```
production: {
            compat: false,
            minify: false,
            env: {
                NODE_ENV: 'production'
            },
            format: 'amd'
        }
```
It seems that this [line](https://github.com/muenzpraeger/create-lwc-app/blob/21047b22f80631feafa6eca6e9a80bf971d0f4a0/packages/lwc-services/src/utils/webpack/webpack-builder.ts#L23)
will ignore the `compat` and `minify` options.

**Comment by muenzpraeger** [comment]
The LWC compiler output is not affected by that line. It's passed as you configure it [to the transform](https://github.com/muenzpraeger/create-lwc-app/blob/main/packages/lwc-webpack-plugin/src/loader.ts#L56).

If you want more granular control I recommend to either use a custom webpack config, or a boilerplate webpack project and the [lwc-webpack-plugin](https://www.npmjs.com/package/lwc-webpack-plugin).

**Comment by banderson5144** [comment]
I guess what I am trying to say is when I run `npm run build` which in turn runs `lwc-services build -m production` and I have `compat` and `minify` false as specified above, it never produces a source map. Only when I run `npm run build:development` which in turn runs `lwc-services build`  will it only produce a source-map. So that's why I am pointing to that line referenced in my original post

**Comment by muenzpraeger** [comment]
Yeah, that's something that's unlikely to change in `lwc-services`. The dedicated webpack plugin is a viable alternative for that.

**Comment by banderson5144** [comment]
@muenzpraeger understood I just wanted to confirm that it wasn't an issue with the parsing of the `lwc-services.config.json`
