### ISSUE TITLE
beta13: jest with TS version fails

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#92]
### Summary

generated code fails tests

### Steps To Reproduce:

1. create with  
? Select a package manager yarn
? Use TypeScript or JavaScript TypeScript
? Register web component Yes
? Use custom Express server configuration No

2. yarn test:unit

### Expected result

tests pass

### Actual result

failures on every createElement

### Additional information

🌟  Using custom configuration from jest.config.js.
🌠  Starting Jest
 FAIL  src/modules/my/greeting/__tests__/greeting.test.js
  ● my-greeting › contains a div that controls animation.

    TypeError: function tmpl($api, $cmp, $slotset, $ctx) {
      const {
        d: api_dynamic,
        h: api_element,
        b: api_bind
      } = $api;
      const {
        _m0
      } = $ctx;
      return [api_element("div", {
        className: $cmp.animationClass,
        key: 1,
        on: {
          "animationend": _m0 || ($ctx._m0 = api_bind($cmp.handleAnimationEnd))
        }
      }, [api_element("span", {
        classMap: {
          "greet": true
        },
        key: 0
      }, [api_dynamic($cmp.greeting)])])];
    } is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

      21 |         const SPEED_CLASS_VALUES = ['fade-slow', 'fade-fast', 'fade-medium'];
      22 | 
    > 23 |         const element = createElement('my-greeting', {
         |                         ^
      24 |             is: MyGreeting
      25 |         });
      26 |         document.body.appendChild(element);

      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:5353:13)
      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:6186:15)
      at Object.createElement (src/modules/my/greeting/__tests__/greeting.test.js:23:25)

  ● my-greeting › contains a span tag that displays the greeting message.

    TypeError: function tmpl($api, $cmp, $slotset, $ctx) {
      const {
        d: api_dynamic,
        h: api_element,
        b: api_bind
      } = $api;
      const {
        _m0
      } = $ctx;
      return [api_element("div", {
        className: $cmp.animationClass,
        key: 1,
        on: {
          "animationend": _m0 || ($ctx._m0 = api_bind($cmp.handleAnimationEnd))
        }
      }, [api_element("span", {
        classMap: {
          "greet": true
        },
        key: 0
      }, [api_dynamic($cmp.greeting)])])];
    } is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

      37 |         const INITIAL_GREETING = 'Hello';
      38 | 
    > 39 |         const element = createElement('my-greeting', {
         |                         ^
      40 |             is: MyGreeting
      41 |         });
      42 |         document.body.appendChild(element);

      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:5353:13)
      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:6186:15)
      at Object.createElement (src/modules/my/greeting/__tests__/greeting.test.js:39:25)

 FAIL  src/modules/my/app/__tests__/app.test.js
  ● my-app › contains a link to the LWC documentation with target set to _blank

    TypeError: function tmpl($api, $cmp, $slotset, $ctx) {
      const {
        c: api_custom_element,
        h: api_element,
        t: api_text
      } = $api;
      return [api_element("div", {
        classMap: {
          "center": true,
          "greeting": true
        },
        key: 1
      }, [api_custom_element("my-greeting", _greeting.default, {
        props: {
          "speed": "medium"
        },
        key: 0
      }, [])]), api_element("div", {
        classMap: {
          "center": true
        },
        key: 3
      }, [api_element("img", {
        attrs: {
          "src": "/resources/lwc.png"
        },
        key: 2
      }, [])]), api_element("div", {
        classMap: {
          "center": true
        },
        key: 10
      }, [api_element("div", {
        classMap: {
          "container": true
        },
        key: 7
      }, [api_element("p", {
        classMap: {
          "info": true
        },
        key: 6
      }, [api_text("Edit "), api_element("strong", {
        classMap: {
          "code": true
        },
        key: 4
      }, [api_text("src/modules/my/app/app.html")]), api_element("br", {
        key: 5
      }, []), api_text("and save for live reload.")])]), api_element("div", {
        key: 9
      }, [api_element("a", {
        classMap: {
          "link": true
        },
        attrs: {
          "href": "https://lwc.dev",
          "target": "_blank"
        },
        key: 8
      }, [api_text("Learn LWC")])])])];
    } is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

      19 | 
      20 |     it('contains a link to the LWC documentation with target set to _blank', () => {
    > 21 |         const element = createElement('my-app', {
         |                         ^
      22 |             is: MyApp
      23 |         });
      24 |         document.body.appendChild(element);

      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:5353:13)
      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:6186:15)
      at Object.createElement (src/modules/my/app/__tests__/app.test.js:21:25)

  ● my-app › contains a link to the LWC documentation with https://

    TypeError: function tmpl($api, $cmp, $slotset, $ctx) {
      const {
        c: api_custom_element,
        h: api_element,
        t: api_text
      } = $api;
      return [api_element("div", {
        classMap: {
          "center": true,
          "greeting": true
        },
        key: 1
      }, [api_custom_element("my-greeting", _greeting.default, {
        props: {
          "speed": "medium"
        },
        key: 0
      }, [])]), api_element("div", {
        classMap: {
          "center": true
        },
        key: 3
      }, [api_element("img", {
        attrs: {
          "src": "/resources/lwc.png"
        },
        key: 2
      }, [])]), api_element("div", {
        classMap: {
          "center": true
        },
        key: 10
      }, [api_element("div", {
        classMap: {
          "container": true
        },
        key: 7
      }, [api_element("p", {
        classMap: {
          "info": true
        },
        key: 6
      }, [api_text("Edit "), api_element("strong", {
        classMap: {
          "code": true
        },
        key: 4
      }, [api_text("src/modules/my/app/app.html")]), api_element("br", {
        key: 5
      }, []), api_text("and save for live reload.")])]), api_element("div", {
        key: 9
      }, [api_element("a", {
        classMap: {
          "link": true
        },
        attrs: {
          "href": "https://lwc.dev",
          "target": "_blank"
        },
        key: 8
      }, [api_text("Learn LWC")])])])];
    } is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

      31 | 
      32 |     it('contains a link to the LWC documentation with https://', () => {
    > 33 |         const element = createElement('my-app', {
         |                         ^
      34 |             is: MyApp
      35 |         });
      36 |         document.body.appendChild(element);

      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:5353:13)
      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:6186:15)
      at Object.createElement (src/modules/my/app/__tests__/app.test.js:33:25)

  ● my-app › contains one active custom element my-greeting

    TypeError: function tmpl($api, $cmp, $slotset, $ctx) {
      const {
        c: api_custom_element,
        h: api_element,
        t: api_text
      } = $api;
      return [api_element("div", {
        classMap: {
          "center": true,
          "greeting": true
        },
        key: 1
      }, [api_custom_element("my-greeting", _greeting.default, {
        props: {
          "speed": "medium"
        },
        key: 0
      }, [])]), api_element("div", {
        classMap: {
          "center": true
        },
        key: 3
      }, [api_element("img", {
        attrs: {
          "src": "/resources/lwc.png"
        },
        key: 2
      }, [])]), api_element("div", {
        classMap: {
          "center": true
        },
        key: 10
      }, [api_element("div", {
        classMap: {
          "container": true
        },
        key: 7
      }, [api_element("p", {
        classMap: {
          "info": true
        },
        key: 6
      }, [api_text("Edit "), api_element("strong", {
        classMap: {
          "code": true
        },
        key: 4
      }, [api_text("src/modules/my/app/app.html")]), api_element("br", {
        key: 5
      }, []), api_text("and save for live reload.")])]), api_element("div", {
        key: 9
      }, [api_element("a", {
        classMap: {
          "link": true
        },
        attrs: {
          "href": "https://lwc.dev",
          "target": "_blank"
        },
        key: 8
      }, [api_text("Learn LWC")])])])];
    } is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

      43 | 
      44 |     it('contains one active custom element my-greeting', () => {
    > 45 |         const element = createElement('my-app', {
         |                         ^
      46 |             is: MyApp
      47 |         });
      48 |         document.body.appendChild(element);

      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:5353:13)
      at getComponentDef (node_modules/@lwc/engine/dist/engine.cjs.js:6186:15)
      at Object.createElement (src/modules/my/app/__tests__/app.test.js:45:25)

Test Suites: 2 failed, 2 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        5.651s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by muenzpraeger** [comment]
Yup, that's a known issue. @trevor-bliss - that's more your domain. Is it something in `lwc-test`?

**Comment by mshanemc** [comment]
@muenzpraeger would you be willing to open your known issues, in the interest of helping people work more efficiently?

**Comment by muenzpraeger** [comment]
Will do for others. Although this is the only one that I am aware of anyway.

**Comment by trevor-bliss** [comment]
I need more information to debug. What version of Jest? What version of Typescript? What is the full Jest config? Maybe sharing a branch would be easiest.

Jest 24 comes with Typescript support out of the box but babel needs to be configured correctly.

https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly#typescript-support

**Comment by muenzpraeger** [comment]
I'm just using `lwc-jest` and it's preset.

Doesn't the transform happen in the [lwc jest-transformer](https://github.com/salesforce/lwc-test/blob/master/packages/@lwc/jest-transformer/src/index.js)?

**Comment by trevor-bliss** [comment]
`@salesforce/sfdx-lwc-jest` uses Jest 24 so that part is fine. Yeah the `@lwc/jest-transformer` package you linked to is where the transform happens.

I wonder if adding `@babel/preset-typescript` to the presets section of the `babel.config.js` will fix this. That's what the core LWC framework does for their unit tests (though they don't use the preset or transformer so not sure if it will get picked up with our custom transformer).

https://github.com/salesforce/lwc/blob/master/babel.config.js#L7

**Comment by muenzpraeger** [comment]
After digging the LWC core code there are a couple of things:

The LWC compiler transforms JS, not TS, with a [fixed Babel config](https://github.com/salesforce/lwc/blob/master/packages/@lwc/compiler/src/babel-plugins.ts). That means `lwc-jest` needs to run an additional step for transforming TS to JS - before passing it to the LWC compiler [here](https://github.com/salesforce/lwc-test/blob/master/packages/@lwc/jest-transformer/src/index.js#L56).

Additionally the `@lwc/jest-preset` doesn't know about TS (see `moduleFileExtensions` and `transform` in the [package](https://github.com/salesforce/lwc-test/blob/master/packages/@lwc/jest-preset/jest-preset.js)). For my take we can add it there, and I'm also open to override that with a custom `jest.config.js` on a project level.

**Comment by muenzpraeger** [comment]
FWIW, the latest `beta` has a fix in it (I branched out from 'lwc-test' till it's in there for beta purposes).

**Comment by sunnymsf** [comment]
Hi, @muenzpraeger any update on this?

I'm still facing the issue with the latest version saying, can't find module '@lwc/engine'

**Comment by muenzpraeger** [comment]
@sunnymsf That has been fixed long ago.
