### ISSUE TITLE
TS flavored generated code should support TS tests

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#93]
### Summary

converting existing jest file to ts causes test failures

### Steps To Reproduce:

1. get tests passing as js on an existing repo
2. convert app's js files to ts
3. yarn test:unit

### Expected result

selecting TS for project yields 
1. test in ts
2. properly configured jest.config for ts testing

### Actual result

Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

**Comment by muenzpraeger** [comment]
First #92 needs to be fixed to make that happen.

And then there's the test file matching. This needs to be added to the Jest config.

`testMatch: ['**/__tests__/**/?(*.)(spec|test).ts']`

Either I add it "manually" to a projects `jest.config.js` file. Or we add it as default to `@lwc/jest-preset` in the PR for #92.

Thoughts @trevor-bliss?

**Comment by trevor-bliss** [comment]
I think it'd be fine to update the `testMatch` in the preset to match against test files that end in `js` or `ts` files.
