### ISSUE TITLE
beta13: export default class is trying to find a .html in ts files

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/create-lwc-app#94]
### Summary

```typescript
export default class Foo {
  public id: string = 'bar';
}
```

### Steps To Reproduce:

1.  Try to import the above class in a component while it's in the same folder. It tries loading `foo.html`.

### Expected result

It should import the file and not look for a `.html` file.

### Actual result

It appears to be trying to resolve a component. It doesn't match the parent folder so it shouldn't be doing that.

### Additional information

n/a

**Comment by muenzpraeger** [comment]
I can't repro, looks valid to me.

![2019-09-05_11-42-56](https://user-images.githubusercontent.com/2205451/64331103-7be1fb00-cfd2-11e9-9dd4-000a79fd426a.png)

**Comment by Templarian** [comment]
Yours works, but just initializing the class like below fails.

![Image 9-5-19 at 12 03 PM](https://user-images.githubusercontent.com/338885/64363028-438fec00-cfd5-11e9-80ab-734855f3fd1a.jpg)

**Comment by mshanemc** [comment]
I could repro this, too on beta-14, using default export (something I wouldn't normally do)

<img width="1431" alt="Screen Shot 2019-09-05 at 6 27 27 PM" src="https://user-images.githubusercontent.com/4261788/64390491-2d9d1e00-d00b-11e9-8440-6ae2a32daefb.png">

Named export seems to work fine, though

<img width="1387" alt="Screen Shot 2019-09-05 at 6 31 45 PM" src="https://user-images.githubusercontent.com/4261788/64390705-82d92f80-d00b-11e9-982f-d164737d5061.png">

**Comment by Templarian** [comment]
I'm not really familiar with babel, but wondering if we need to use `@babel/plugin-proposal-class-properties` instead of just the syntax one that parses the content.

https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

**Comment by Templarian** [comment]
https://github.com/salesforce/lwc/issues/1497

Haven't looked into this further, but the above will probably resolve this.

**Comment by muenzpraeger** [comment]
Already fixed with latest beta. See #104
