### ISSUE TITLE
beta14: Windows 10: npx lwc-create-app@beta not installing lwc-service beta

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/create-lwc-app#95]
### Summary

When using the `npx lwc-create-app@beta test` command on a Windows 10 box with NPM 10/12 it is giving the options for typescript, but installs stable branch and keeps it .js

### Steps To Reproduce:

1.  Load up Windows box
1. Run `npx lwc-create-app@beta test`
1. Press enter a bunch

### Expected result

It should install the beta.

### Actual result

It installs the stable lwc-service without ts.

### Additional information

I can look into debugging this later. Feel like it worked on one of the earlier betas I was testing with. 😕 My mac correctly sets up the beta.

**Comment by muenzpraeger** [comment]
I can't repro (have no Windows machine). Is that still open?

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/64885413-bc242780-d629-11e9-8a75-88eded55167f.png)

It's like it doesn't select the beta, but it's asking for TypeScript in the setup questions.

**Comment by muenzpraeger** [comment]
Ha! It’s `create-lwc-app` for npx. ;-)

**Comment by Templarian** [comment]
oops. Good catch! 🤦‍♂
