### ISSUE TITLE
generated code is uncommittable (eslint rules)

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#96]
### Summary

generating the code doesn't have a lint error on the file, but does when husky pre-commits run.

### Steps To Reproduce:

npx create-lwc-app@beta electron-web-lwc
git commit -m 'generate'

### Expected result

commit

### Actual result

✖ eslint found some errors. Please fix them and try committing again.

/Users/shane.mclaughlin/code/electron-web-lwc/src/modules/my/greeting/greeting.ts
30:29  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
61:9   warning  Restricted async operation "setTimeout"                                    @lwc/lwc/no-async-operation

### Additional information

linter rules should match during compile and commit

**Comment by muenzpraeger** [comment]
Will investigate. Although I am wondering how much can be done, as linting errors come from eslint. The project just provides configs and dependencies.

**Comment by mshanemc** [comment]
this is just a syntax your eslint rules doesn't like. 

bad:  if (SPEED_CLASS_MAP.hasOwnProperty(value)) 
good: if (Object.prototype.hasOwnProperty.call(SPEED_CLASS_MAP, value))
