### ISSUE TITLE
import of createElement and module resolution like jest fails in regular lwc

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#97]
### Summary

I'm using createElement to do a router like this example:
https://github.com/pmdartus/rcast/blob/master/src/client/modules/rcast/app/app.js

### Steps To Reproduce:

This'll be ok in jest, but not OK in another LWC for the linter

import { createElement } from 'lwc';
import MyApp from 'my/app';

### Expected result

linter lets you do it, resolves modules

### Actual result

Module '"lwc"' has no exported member 'createElement'.
Cannot find module 'my/whatever'.
Property 'querySelector' does not exist on type 'ShadowRootTheGoodPart'.

### Additional information
It runs fine on local dev server.  It's just more false positives on the linter.

**Comment by muenzpraeger** [comment]
Is it a TS project? If so it’s because your project is missing corresponding `d.ts` files. That’s part of the VS Code enhancing for LWC OSS.

**Comment by mshanemc** [comment]
Yes.  Where do I get those?  Why wouldn’t create-app add them (since not everyone will be using vscode/extensions) or at least make sure they exist?

**Comment by muenzpraeger** [comment]
They are located in any `.sfdx/typings` folder in an SFDX project.

It will be provided by the language server within VS Code. Especially when it comes to maintainability it doesn't make sense to have that spread across different tools.
