### ISSUE TITLE
module resolution fails when converting js files to ts 

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#98]
### Summary

module resolution fails when converting js files to ts 

### Steps To Reproduce:

create a project with yarn/ts
create an LWC with .html, .js
yarn watch, open :3001 in browser
change the file's extension from .js to .ts

### Expected result

reloads

### Actual result

can't find the js file anymore.  You have to ctrl+c the watch and then yarn watch again.

### Additional information

migrating from js projects is a pretty typical ts workflow.  Fully expect to see `create lwc` in vscode for lwc-oss eventually, but it'll probably create js files.

**Comment by muenzpraeger** [comment]
Yeah, that’s the underlying LWC Module resolution. Not much I can do there.

LWC OSS in VS Code is coming. ;-)

https://github.com/forcedotcom/salesforcedx-vscode/issues/1599
